### ISSUE TITLE
Recupero idpName

### ISSUE THREAD

**Issue by AndreaPetrelli** [italia/spid-aspnetcore#10]
Attualmente l'idpName scelto tramite il pulsante viene recuperato tramite il parametro della query "idpName". 

Per pulizia proporrei di provare a recuperarlo anche dai parametri dell'AuthenticationProperties

https://docs.microsoft.com/it-it/dotnet/api/microsoft.aspnetcore.authentication.authenticationproperties.parameters?view=aspnetcore-5.0

che possono essere assegnati nella creazione dell'AuthenticationProperties.

https://github.com/AndreaPetrelli/spid-aspnetcore/blob/5e86ef914e2b20272cfad9e4b31ba7a61b934ebd/SPID.AspNetCore.Authentication/SPID.AspNetCore.Authentication/SpidHandler.cs#L102

**Comment by danielegiallonardo** [comment]
Nulla vieta di impostare un numero arbitrario di parametri nell'AuthenticationProperties, i motivi per i quali l'idpName non vien letto da lì sono sostanzialmente 2:
- La libreria andrebbe usata congiuntamente con il TagHelper che genera i pulsanti SPID, che aggiungono l'idpName in QueryString, per cui si aspetta di trovare lì questa impostazione
- Il nome del parametro può essere arbitrario, per cui non c'è modo di forzarne uno, se non by-convention.

**Comment by AndreaPetrelli** [comment]
Il problema che mi sono trovato davanti è che l'attuale implementazione non onora il ReturnUrl (utile sopratutto quando viene realizzato un server di identità tramite IdentityServer o OpenIddict), cosa che ho gestito reimplementando la gestione della generazione dei pulsanti in modo simile al template standard della pagina di login:

https://github.com/dotnet/aspnetcore/blob/main/src/Identity/UI/src/Areas/Identity/Pages/V4/Account/Login.cshtml

Avrei potuto ripetere il returnUrl per ogni pulsante ma avrebbe caricato la pagina di informazioni ripetute.

Non sarebbe possibile definire una costante per il nome del parametro?

**Comment by danielegiallonardo** [comment]
Anche io utilizzo questa libreria insieme ad IdentityServer, e ho questa integrazione (che segue la falsariga del template scaffolded per le login esterne, tipo Facebook o Google):

Action di Login:
```csharp
[HttpGet]
public async Task<IActionResult> Login(string returnUrl = null)
{
     // Codice di rendering della pagina di login
     // ........

     ViewData["ReturnUrl"] = returnUrl;
     return View(model);
}
```

View di Login:
```razor
<!-- Codice della pagina di Login...... -->
<spid-providers challenge-url="@Url.Action("ExternalLogin", "Account", new { provider = SpidDefaults.AuthenticationScheme, returnUrl = ViewData["ReturnUrl"] })"
                size="Medium"
                class="text-left"></spid-providers>
```

Action richiamata dal pulsante SPID:
```csharp
[HttpPost]
[HttpGet]
public IActionResult ExternalLogin(string provider, string returnUrl = null)
{
            var redirectUrl = Url.Action(nameof(ExternalLoginCallback), "Account", new { returnUrl });
            var properties = _signInManager.ConfigureExternalAuthenticationProperties(provider, redirectUrl);
            return Challenge(properties, provider);
}
```

Al termine del giro verso-da SPID, verrà effettuato il redirect, dalla libreria, alla returnUrl specificata, che sarà la ExternalLoginCallback, con un parametro returnUrl che sarà la risorsa originariamente richiesta ad IdentityServer:

```csharp
[HttpGet]
public async Task<IActionResult> ExternalLoginCallback(string returnUrl = null, string remoteError = null)
{
            if (remoteError != null)
            {
                ErrorMessage = $"Error from external provider: {remoteError}";
                return RedirectToAction(nameof(Login));
            }
            var info = await _signInManager.GetExternalLoginInfoAsync();
            if (info == null)
            {
                return RedirectToAction(nameof(Login));
            }

            // Sign in the user with this external login provider if the user already has a login.
            var result = await _signInManager.ExternalLoginSignInAsync(info.LoginProvider, info.ProviderKey, isPersistent: false, bypassTwoFactor: true);
            if (result.Succeeded)
            {
                var user = await _userManager.FindByLoginAsync(info.LoginProvider, info.ProviderKey);
                if (user != null)
                {
                    IdentityServer4.Models.AuthorizationRequest context = null;
                    string clientId = null;
                    try
                    {
                        context = await _interaction.GetAuthorizationContextAsync(returnUrl);
                        clientId = context?.Client?.ClientId;
                    }
                    catch { }
                    // Do something with the User (e.g. audit the login)
                    // ......
                }
                return RedirectToLocal(returnUrl);
            }
            if (result.IsLockedOut)
            {
                return RedirectToAction(nameof(Lockout));
            }
            else
            {
                // If the user does not have an account, then ask the user to create an account.
               // after the registration, the user will return here and will be redirected to the final location

                return View(nameof(ExternalLogin), new ExternalLoginViewModel
                {
                     // .......
                });
            }
        }
```

**Comment by AndreaPetrelli** [comment]
Si, l’ho gestita nello stesso modo come da template. Quello che non mi faceva impazzire era la ripetizione del returnUrl per ogni provider.

**Comment by danielegiallonardo** [comment]
Le implementazioni possono essere molteplici, ma per quanto riguarda l'idpName non posso prevedere qualunque implementazione, e, per motivi di consistenza e testabilitá l'integrazione suggerita (e consigliata) è quella con il TagHelper interno. Chiudo la issue.
