### ISSUE TITLE
Perdita della sessione al rientro sull'Error action

### ISSUE THREAD

**Issue by gianlucabertani** [italia/spid-aspnetcore#16]
Siamo partiti dall'applicazione Asp.Net e l'abbiamo personalizzata, introducendo l'uso di una sessione su cookie (quindi i classici `app.UseSession()` e `services.AddSession(opts)`) per poter garantire che richieste contemporanee da parte di utenti diversi non si sovrappongano.

Il primo punto dove usiamo la sessione è nell'Index action, dove ci salviamo una serie di parametri di rientro. 

Quando l'autenticazione con l'IdP va a buon fine e rientriamo nella LoggedIn action, la sessione è corretta e ritroviamo i parametri salvati. 

Quando l'autenticazione invece fallisce per qualsiasi motivo, rientriamo nell'Error action e la sessione è diversa.

Non riusciamo a capire la ragione di questo comportamento. Qualche aiuto?

**Comment by danielegiallonardo** [comment]
Non è necessario usare la sessione per correlare le richieste e le risposte o per orchestrare richieste diverse da parte di utenti diversi, la libreria già si occupa di queste questioni, ed in particolare salva le informazioni che le occorrono all'interno del cookie criptato "Spid.Properties". Occhio che il cookie è "Secure", per cui è necessario verificare che le pagine siano ospitate in https.
Per altre questioni "esterne" rispetto all'uso specifico della libreria (visto che la libreria non usa, e quindi non invalida, la sessione) non so darti molto aiuto senza vedere il codice, ma, appunto, in quel caso è codice esterno.

**Comment by gianlucabertani** [comment]
Eppure qualche differenza ci deve essere, perché trattiamo la sessione esattamente nello stesso modo tra le due action, ma in un caso c'è e nell'altro no.

Dovrebbe essere semplice da replicare, partendo dall'applicazione Asp.Net così com'è:
- Si aggiunge la gestione della sessione via cookies in Startup.cs.
- Nella Index action si salva un valore convenzionale in sessione (`HttpContext.Session`).
- Nella LoggedIn action si prova a recuperarlo e loggarlo.
- Idem nella Error action, si prova a recuperarlo e loggarlo.

Fatto questo, usando il Validator locale già si dovrebbe vedere il problema. Se la risposta dal Validator è positiva, nella LoggedIn dovrebbe recuperare correttamente il valore in sessione. Viceversa, se la risposta dal Validator è negativa (per es. uno qualsiasi degli errori di credenziali), il valore sulla sessione dovrebbe essere assente.

**Comment by sm15455** [comment]
Come detto da Daniele, la libreria non fa uso di variabili di sessione o affini. Tuttavia, per essere sicuri di non avere problemi, prova a inviare un progetto di test che riproduce il problema e proveremo a dargli un'occhiata.

**Comment by peppelinux** [comment]
Sul cookie, oltre a SECURE, che sia samesite none altrimenti Chrome lo blocca e httponly come buona pratica . FYI

**Comment by danielegiallonardo** [comment]
Si Giuseppe, è già impostato come SameSite=None, non lo avevo specificato nella risposta perchè non mi sembrava pertinente al problema specifico, ma hai fatto bene a sottolinearlo

**Comment by danielegiallonardo** [comment]
Se non ci sono aggiornamenti su questa Issue sarei propenso a chiuderla.
