### ISSUE TITLE
Accesso SPID L3

### ISSUE THREAD

**Issue by dassocec** [italia/spid-aspnetcore#20]
Buongiorno,
in fase di approvazione da agid, ricevo che il test 96 non viene superato.

Effettuando il test con il demo validator, effettivamente ricevo questo errore:

An error was encountered while handling the remote login. AuthnContextClassRef non valido.

**Comment by danielegiallonardo** [comment]
Potresti allegare la request e la response?

**Comment by danielegiallonardo** [comment]
Inoltre, quale versione della libreria viene utilizzata?

**Comment by dassocec** [comment]
Utilizzo l'ultima versione aggiornata. 
[L3.zip](https://github.com/italia/spid-aspnetcore/files/7216083/L3.zip)

Ho notato che nella request viene riportato SPIDL2; come posso testare il login SPIDL3 sul demo validator?

**Comment by danielegiallonardo** [comment]
Ho chiesto della versione perchè in alcune versioni precedenti c'era un bug relativo al controllo del campo AuthnContextClassRef, che è stato poi risolto. Attualmente (v.1.3.4) la libreria verifica che il livello della response non sia inferiore a quello della request (comparison=minimum). Per quanto riguarda il livello, è possibile impostare, per ogni IdentityProvider, il "SecurityLevel" da utilizzare nelle request. Ho aggiornato la documentazione a tal proposito.

**Comment by danielegiallonardo** [comment]
Ho eseguito il test 96 sul validator (https://demo.spid.gov.it/validator#/response/test-suite-1/96), con la versione 1.3.4 della libreria nuget, e il messaggio di risposta viene validato correttamente, inviando L2 nella request e ricevendo L3 nella response.

**Comment by dassocec** [comment]
Forse mi sono perso io qualche passaggio? 
Mi potresti dire gentilmente in quale parte del codice è stato risolto il bug e viene effettuato questo controllo? 

Dalla versione 1.2.0 come posso passare alla 1.3.4 senza sovrascrivere tutto il progetto?

**Comment by danielegiallonardo** [comment]
Perdonami, ma quindi non hai utilizzato la liberia nuget? Hai clonato e importato nella solution il codice sorgente di questo repo?
Nel caso di utilizzo della libreria nuget (che consiglio fortemente, ed è l'approccio riportato in documentazione) l'aggiornamento è banale, si tratta di aggiornare la versione. 
Se invece hai importato il codice io non posso sapere che modifiche o customizzazioni hai apportato, e l'unica cosa che posso dirti è di analizzare la history su git.
Per il futuro (e approfitterei di questa occasione) ti suggerisco di utilizzare la libreria nuget, che ha tutti i punti di estensione che servono per eventuali customizzazioni.

**Comment by dassocec** [comment]
Ho scaricato il progetto dal repo e l'ho aperto con Visual studio, poi ho effettuato qualche personalizzazione solo nelle pagine cshtml.

Ho provato ad installare il pacchetto nuget ma ricevo questo:
Errore NuGet NU1108

**Comment by danielegiallonardo** [comment]
Ti consiglio di eliminare tutto il codice relativo alla libreria, ivi compresi eventuali riferimenti a pacchetti nuget utilizzati dal codice della libreria, e di riprovare a integrare la libreria nuget. Chiudo la issue
