### ISSUE TITLE
NotBefore di Condition maggiore dell'ora di ricezione della response

### ISSUE THREAD

**Issue by AntonioArgentieri93** [italia/spid-aspnetcore#23]
Stavo verificando la mia implementazione di autenticazione SPID che ho realizzato attraverso le vostre librerie. Al momento riesco ad inviare correttamente la request e a ricevere la response senza alcun problema.

Durante la validazione della response il programma va in eccezione nel momento in cui avviene il confronto fra NotBefore di Condition e il campo DataTimeOffset.UtcNow.
Effettivamente in debug ho notato che NotBefore sia sempre avanti di alcuni secondi (quindi maggiore) rispetto all'ora di DataTimeOffset.UtcNow invalidando così la response. La stessa cosa succede anche tramite la validazione con SPID Validator.

C'è qualcosa che mi sfugge nella procedura o si tratta effettivamente di un bug?

**Comment by Antonyclar** [comment]
Ok allora proverò a testarlo lì e vediamo cosa succede, per il momento grazie.
