### ISSUE TITLE
Generatore di metadata per Service Provider

### ISSUE THREAD

**Issue by pampua84** [italia/spid-aspnetcore#24]
Ciao,
ho visto la vostra libreria che mi sembra un'ottima soluzione  per eseguire un'integrazione con SPID in modo veloce e fluente. Unica cosa, sarebbe comoda una classe che generi i metadata per i ServiceProvider e che li esponga automaticamente su un enpoint (esempio /saml/metadata-spid )dell'applicazione, in modo da fornire direttamente l'uri a cui l'idp puo' far riferimento per integrare i metadata.

Se mi sbaglio e tale funzionalità esiste già, potete indicarmi qual'è?

Grazie

**Comment by danielegiallonardo** [comment]
Ottimo spunto. No, attualmente non c'è una classe in questa libreria che emetta dinamicamente il metadata per un SP, ma credo sia un'ottima idea per lo sviluppo di una funzionalità futura, sulla falsa riga di quello che WCF faceva rispetto ai metadata endpoint. Allo stato attuale la libreria parte dal presupposto che i metadati siano stati già generati e validati in una fase preliminare.
Ad ogni modo tengo la issue aperta e vedo di pianificare la cosa per uno sviluppo futuro, la creazione dei metadati è una faccenda abbastanza ampia e complessa, considerati gli avvisi SPID che la riguardano.

**Comment by pampua84** [comment]
Ciao Daniele, 
sono pienamente d'accordo per su quanto hai detto. Sullo SPID hanno imposto dei vincoli molto forti sui metadata, che possono creare più di un problema per generarli, visto la forte customizzazione.
Spero di poter collaborare in futuro a questa feature.

**Comment by danielegiallonardo** [comment]
Ho pubblicato la versione 1.3.7 della libreria, che contiene il codice per la generazione dei metadata dei Service Provider. 
Ho testato tutti i profili utilizzando spid_sp_test.
Ora aggiorno la documentazione, grazie per lo spunto
