### ISSUE TITLE
Bug ServiceProvider Metadata campi non obbligatori

### ISSUE THREAD

**Issue by pampua84** [italia/spid-aspnetcore#26]
Ciao,
innanzitutto grazie per aver implementato cosi' velocemente la feature suggerita. 
Ho riscontrato pero' un'incogruenza, dalle specifiche di SPID, per i metadata dei SP i seguenti campi non sembrano essere obbligatori:

```
BillingCompany = "Billing company",
BillingEmailAddress = "billing@email.com",
BillingTelephoneNumber = "+3908241748276",
CessionarioCommittenteIdCodice = "+390123456789",
CessionarioCommittenteIdPaese = "IT",
CessionarioCommittenteDenominazione = "Azienda_Destinataria_Fatturazione",
CessionarioCommittenteCAP = "12345",
CessionarioCommittenteComune = "Comune",
CessionarioCommittenteIndirizzo = "Indirizzo",
CessionarioCommittenteNazione = "Nazione",
CessionarioCommittenteNumeroCivico = "17",
CessionarioCommittenteProvincia = "XX"
```
come da documentazione: https://docs.italia.it/italia/spid/spid-regole-tecniche/it/stabile/metadata.html. Se provo a rimuoverli però ottengo un'eccezione

```
Exception: No CessionarioCommittenteIdCodice/CessionarioCommittenteIdPaese or CessionarioCommittenteCodiceFiscale were specified
```
Tali dati dovrebbero essere obbligatori solo in caso di: 'metadata SP per Fatturazione'.
Grazie

**Comment by danielegiallonardo** [comment]
Salve,
da specifiche SPID linkate leggo:

"ContactPerson (1 o 2 occorrenze) — Tag utilizzato per veicolare le informazioni per contattare il soggetto cui il metadata afferisce. Ogni occorrenza è dotata dei seguenti attributi:
contactType — L’occorrenza obbligatoria di ContactPerson è valorizzata con other; l’ulteriore occorrenza, obbligatoria per i soli SP privati, è valorizzata con billing. 
[....] 
L’occorrenza di ContactPerson con l’attributo contactType valorizzato come billing è obbligatoria in caso sia presente l’estensione Private nel tag Extensions (dell’occorrenza di ContactPerson con l’attributo contactType valorizzato come other). Contiene le informazioni fiscali minime per l’individuazione del soggetto che sarà il destinatario di fatturazione elettronica, in qualità di committente, da parte degli IdP. "

La mia interpretazione è (stata) che per i soggetti "privati" tale campo è obbligatorio. Potresti indicarmi la parte delle specifiche dove secondo te è riportato che i dati di fatturazione sono opzionali?
Grazie.

**Comment by pampua84** [comment]
Ciao ti riporto l'esempio dei metadata del SP che trovi alla fine della pagina:

```
<md:EntityDescriptor xmlns:md="urn:oasis:names:tc:SAML:2.0:metadata"
    xmlns:spid="https://spid.gov.it/saml-extensions"
    xmlns:md="urn:oasis:names:tc:SAML:2.0:metadata"
    entityID="https://spid.serviceprovider.it"
    ID="_0j40cj0848d8e3jncjdjss...">
    <ds:Signature xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
        [...]
    </ds:Signature>
    <md:SPSSODescriptor
        protocolSupportEnumeration="urn:oasis:names:tc:SAML:2.0:protocol"
        AuthnRequestsSigned="true"
        WantAssertionsSigned="true">
        <md:KeyDescriptor use="signing">
            [...]
        </md:KeyDescriptor>
        <SingleLogoutService
            Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST"
            Location="https://spid.serviceprovider.it/slo-location"
            ResponseLocation="https://spid.serviceprovider.it/slo-location"/>
        <NameIDFormat>urn:oasis:names:tc:SAML:2.0:nameid-format:transient</NameIDFormat>
        <md:AssertionConsumerService
            index="0" isDefault="true"
            Location="https://spid.serviceprovider.it/sso-location"
            Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST"/>
        <md:AssertionConsumerService
            index="1"
            Location="https://spidSP.serviceProvider.it/sso-location"
            Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST"/>
        <md:AttributeConsumingService index="0">
            <md:ServiceName xml:lang="it">Set 0</md:ServiceName>
            <md:RequestedAttribute Name="name"/>
            <md:RequestedAttribute Name="familyName"/>
            <md:RequestedAttribute Name="fiscalNumber"/>
            <md:RequestedAttribute Name="email"/>
        </md:AttributeConsumingService>
            <md:AttributeConsumingService index="1">
            <md:ServiceName xml:lang="it">Set 1</md:ServiceName>
            <md:RequestedAttribute Name="spidCode"/>
            <md:RequestedAttribute Name="fiscalNumber"/>
        </md:AttributeConsumingService>
    </md:SPSSODescriptor>
    <md:Organization>
        <OrganizationName xml:lang="it">Service provider</OrganizationName>
        <OrganizationDisplayName xml:lang="it">Nome service provider</OrganizationDisplayName>
        <OrganizationURL xml:lang="it">http://spid.serviceprovider.it</OrganizationURL>
    </md:Organization>
    <md:ContactPerson contactType="other">
        <md:Extensions>
            <spid:VATNumber>IT12345678901</spid:VATNumber>
            <spid:FiscalCode>XYZABCAAMGGJ000W</spid:FiscalCode>
            <spid:Private/>
        </md:Extensions>
        <md:EmailAddress>tech-info@example.org</md:EmailAddress>
        <md:TelephoneNumber>+39 8472345634785</md:TelephoneNumber>
    </md:ContactPerson>
</md:EntityDescriptor>
```

Dove non sono obbligatori i campi che ti ho indicato.

**Comment by danielegiallonardo** [comment]
Da avviso SPID n.29 (https://www.agid.gov.it/sites/default/files/repository_files/spid-avviso-n29v3-specifiche_sp_pubblici_e_privati_0.pdf):
"L’occorrenza di ContactPerson con l’attributo contactType valorizzato come billing è obbligatoria in
caso sia presente l’estensione Private nel tag Extensions"
Il metadata che hai riportato come esempio, presente su docs.italia, probabilmente non ha recepito l'avviso n.29 ed è fermo ad una versione precedente delle specifiche, e quindi risulta mancante della parte relativa al billing.
Nel dubbio fai sempre riferimento alla documentazione ufficiale di AGID.
Chiudo.
