### ISSUE TITLE
Errore con Poste Italiane e Logout

### ISSUE THREAD

**Issue by dassocec** [italia/spid-aspnetcore#27]
A questo link è stata pubblicata la webapp opportunamente modificata per le nostre esigenze:
https://pdc.cieccisrl.net:444/

In fase di login con Poste Italiane, si verifica un errore: "IssueInstant non presente, malformato o arrivo non della richiesta con l'orario di richiesta". Provo a sincronizzare l'ora del server con il server microsoft, ma dopo un po' il problema si ripresenta.
Invece, accedendo con gli altri IdP, si verifica un errore 404 sul logout: " https://pdc.cieccisrl.net:444/signout-spid non trovata".

Potete aiutarmi a verificare da cosa può dipendere?

**Comment by dassocec** [comment]
A questo link è stata pubblicata la webapp opportunamente modificata per le nostre esigenze:
https://pdc.cieccisrl.net:444/

In fase di login con Poste Italiane, si verifica un errore: "IssueInstant non presente, malformato o non coerente con l'orario di arrivo della richiesta". Provo a sincronizzare l'ora del server con il server microsoft, ma dopo un po' il problema si ripresenta.
Invece, accedendo con gli altri IdP, si verifica un errore 404 sul logout: "https://pdc.cieccisrl.net:444/signout-spid non trovata".

Potete aiutarmi a verificare da cosa può dipendere?

**Comment by danielegiallonardo** [comment]
Conviene che l'orario del server su cui gira la webapp sia costantemente sincronizzato con NTP.
Per quanto riguarda la signout è strano, in POST con Poste funziona (ho verificato ora sul vostro sito di esempio, ed effettua correttamente la chiamata in POST su https://pdc.cieccisrl.net:444/signout-spid). Con gli altri IdP come andate, in POST o in Redirect?

**Comment by dassocec** [comment]
Ok, ho impostato NTP come server di sincronizzazione dell'ora.
Tutti gli IdP sono configurati con il metodo POST.

**Comment by danielegiallonardo** [comment]
La risorsa https://pdc.cieccisrl.net:444/signout-spid in POST esiste, l'ho verificato io stesso facendo la logout da Poste (non ho altri account su altri IdP per provare), per cui l'errore non può essere un 404 su quella risorsa. Verificate, tramite i tool di sviluppo del browser che il 404 sia effettivamente su quella risorsa, e confrontate i vari step di redirect che vengono fatti durante il flusso di logout usando Poste e usando un altro IdP.

**Comment by dassocec** [comment]
Con NamirialID - No resource with given URL found: "https://idp.namirialtsp.com/cas/login?service=https%3A%2F%2Fidp.namirialtsp.com%2Fidp%2FAuthn%2FExtCas%3Fconversation%3De1s1%26forceAuthn%3Dtrue&authnMethod=https%3A%2F%2Fwww.spid.gov.it%2FSpidL2&source=idp.namirialtsp.com%2F%2Fidp%2FAuthn%2FExtCas&orgName=Comune+di+Melfi+-+ufficio+tributi&authnReqId=_43c6fe4f-2310-4cfb-b360-351cbe108d40&entityId=https%3A%2F%2Fpdc.cieccisrl.net%3A444%2Fpub-ag-full&force=true&eType=null&Sign=ajiWL4IShRbKLVxZNZ4h1h5p4LWK4vxvhlGlhVdlRehIQuvyTApm8%2BOfUJicHhhQs85yxZ2bCCFU2ygbzBPoHJa0ltjY0YjwVn3AqFRF3XcnqihvToHXzLYpqziIE7ia4IQqSzn94ol9BArlzu768WzYCxP4iL8Mcv6JWuAGSwmGPhg4PmlUEiju2GxYzup2%2FuB%2B1AIuY3ooHBRk0nHCuRR9%2BaGBoybXEa9xc6RSnghefU0gLF38PYwSDhpUE1cQX0u78RvUagopqseshsbUiO1zXu0HO%2FLKAdRZIMBlx4QGpqHWZ5CD3Kq0p%2B2v1ZX2rwy4tHzVTdo5ENdR8EhfhA%3D%3D"

Cliccando una seconda volta su Logout: "The given key 'IdentityProviderName' was not present in the dictionary."

**Comment by danielegiallonardo** [comment]
L'errore sul secondo click è probabile dipenda dal fatto che la sessione di autenticazione viene chiusa e poi viene fatto il redirect verso l'IdP, quindi cliccando una seconda volta non trova i dati di sessione e va in errore (diciamo che è uno scenario che non dovrebbe presentarsi, ma è corretto che vada in errore, non esistendo più una sessione da chiudere non dovrebbe essere fatto un nuovo logout).
Il primo errore credo sia roba interna di Namirial, non credo abbia nulla a che fare con la webapp o con la libreria.

**Comment by danielegiallonardo** [comment]
Peraltro sto notando che con Namirial i parametri della request stanno in querystring, quindi ci state andando in Redirect, non in POST

**Comment by dassocec** [comment]
Quindi devo modificare il metodo nell'appsettings.json in "redirect"?

**Comment by dassocec** [comment]
gli URI di namirial comunque fanno riferimento a metodi POST:
"SingleSignOnServiceUrl": "https://idp.namirialtsp.com/idp/profile/SAML2/POST/SSO",
"SingleSignOutServiceUrl": "https://idp.namirialtsp.com/idp/profile/SAML2/POST/SLO",

**Comment by danielegiallonardo** [comment]
No, perdonami, ho appena controllato il flusso. Ci andate in POST ma Namirial fa una sua traduzione successiva per andare su CAS in Redirect.
![image](https://user-images.githubusercontent.com/58780951/144641134-df9dad04-1470-4959-aa44-c5815e358ac1.png)
 Ad ogni modo arrivo fino alla form di login, non posso andare avanti perchè non ho credenziali spid su Namirial. In quale fase ricevete l'errore di cui sopra?

**Comment by dassocec** [comment]
Il login va a buon fine. Riesco a visualizzare i dati richiesti. Nel logout. 
![Immagine](https://user-images.githubusercontent.com/73878794/144642808-e89f7e35-f018-46aa-ab4e-0481f3294138.png)
.

**Comment by danielegiallonardo** [comment]
Quell'errore 500 ho paura sia su Namirial. La richiesta di Logout inviata dalla libreria è assolutamente compliant con le specifiche SPID, cosa succeda poi su quel 302 triggerato da Namirial per virare su CAS non è dato saperlo, ma come sospettavo è fuori dallo scope della libreria. Credo vi convenga contattare il supporto di Namirial al riguardo.

**Comment by dassocec** [comment]
Ok. Grazie mille.

**Comment by danielegiallonardo** [comment]
Si però non ho capito l'errore 404 sul logout: " https://pdc.cieccisrl.net:444/signout-spid non trovata", di cui al primo post, dove e quando si verifica

**Comment by dassocec** [comment]
Dopo il login corretto con Namirial, cliccando su Logout.
