### ISSUE TITLE
Errore "AuthnRequest Signature validation" con la generazione dei metadati

### ISSUE THREAD

**Issue by AndreaPetrelli** [italia/spid-aspnetcore#28]
**Describe the bug**
Stavo provando ad usare la generazione dei metadati ma, durante la validazione della richiesta tramite lo SPID Validator, ricevo l'errore 34 - AuthnRequest Signature validation.

Ho provato ad effettuare lo stesso controllo tramite il tool spid-sp-test  ricevendo lo stesso errore:

```
DEBUG:spid_sp_test.authn_request:Running authn request signature validation: xmlsec1 --verify --insecure --id-attr:ID "urn:oasis:names:tc:SAML:2.0:protocol:AuthnRequest" --pubkey-pem /var/folders/2k/j4l2spk552q7hfb81kld90bc0000gn/T/tmp58_20z1i.crt /var/folders/2k/j4l2spk552q7hfb81kld90bc0000gn/T/tmpizbq9995.xml
DEBUG:spid_sp_test.authn_request:/var/folders/2k/j4l2spk552q7hfb81kld90bc0000gn/T/tmp58_20z1i.crt:
unable to load certificate
4753878528:error:0D0680A8:asn1 encoding routines:asn1_check_tlen:wrong tag:crypto/asn1/tasn_dec.c:1149:
4753878528:error:0D07803A:asn1 encoding routines:asn1_item_embed_d2i:nested asn1 error:crypto/asn1/tasn_dec.c:309:Type=X509_CINF
4753878528:error:0D08303A:asn1 encoding routines:asn1_template_noexp_d2i:nested asn1 error:crypto/asn1/tasn_dec.c:646:Field=cert_info, Type=X509
4753878528:error:0906700D:PEM routines:PEM_ASN1_read_bio:ASN1 lib:crypto/pem/pem_oth.c:33:
DEBUG:spid_sp_test.authn_request:The AuthnRequest MUST validate against XSD and MUST have a valid signature
stderr: func=xmlSecOpenSSLAppKeyLoadBIO:file=app.c:line=316:obj=unknown:subj=PEM_read_bio_PrivateKey and PEM_read_bio_PUBKEY:error=4:crypto library function failed:openssl error: 151584876: PEM routines: get_name no start line
func=xmlSecOpenSSLAppKeyLoad:file=app.c:line=218:obj=unknown:subj=xmlSecOpenSSLAppKeyLoadBIO:error=1:xmlsec library function failed:filename=/var/folders/2k/j4l2spk552q7hfb81kld90bc0000gn/T/tmp58_20z1i.crt
Error: xmlSecCryptoAppKeyLoad failed: file=/var/folders/2k/j4l2spk552q7hfb81kld90bc0000gn/T/tmp58_20z1i.crt
Error: failed to load public key from "/var/folders/2k/j4l2spk552q7hfb81kld90bc0000gn/T/tmp58_20z1i.crt".
Error: keys manager creation failed
```

Sembra infatti che il contenuto base64 del tag X509Certificate non contenga un certificato valido per openssl. Guardando il codice, vedo che il metodo Serialize del provider esporta il certificato tramite la funzione GetPublicKey(). Utilizzando invece la funzione Certificate.Export(X509ContentType.Cert) tutto funziona correttamente.

Il certificato è stato generato tramite il tool spid-compliant-certificates installato tramite pip (cosi come spid-sp-test).

Di seguito le versioni:
spid-compliant-certificates 0.3
spid-sp-test 1.1.1
OpenSSL 1.1.1l

**Desktop (please complete the following information):**
 - OS: OSX

**Comment by danielegiallonardo** [comment]
Salve,
ho creato un branch "FixCertificatoSP" con relativa PullRequest, che implementa il fix suggerito.
I test automatici passano, per cui è retrocompatibile, avresti modo di verificare se il fix risolve il problema, di modo tale da procedere poi alla generazione del package e alla chiusura della PR?
Grazie

**Comment by AndreaPetrelli** [comment]
Provato ora, funziona correttamente.

**Comment by danielegiallonardo** [comment]
Perfetto grazie, allora pubblico il package e faccio merge della PR.
