### ISSUE TITLE
AuthRequest formulata in modo errato

### ISSUE THREAD

**Issue by pampua84** [italia/spid-aspnetcore#32]
Ciao,
facendo l'integrazione come SP verso un IdP ricevo sempre l'errore ErrorCode 16, quindi ho esaminato la tabella degli errori di SPID:

[https://www.agid.gov.it/sites/default/files/repository_files/tabella-messaggi-spid-v1.3_0.pdf](url)

che riporta quanto segue:

![image](https://user-images.githubusercontent.com/17255890/146180693-daeaefa2-97cf-431c-803f-d89bfc533187.png)

Esaminando la request che genera la libreria, in effetti sono presenti due attributi (AssertionConsumerServiceURL, AssertionConsumerServiceIndex) che sembrano essere incopatibili:

`<samlp:AuthnRequest xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" ID="_4c255409-f9c9-400d-bad5-f08526143c12" Version="2.0" IssueInstant="2021-12-13T13:00:09.823704Z" Destination="https://........../idp/sso/post" ForceAuthn="true" AssertionConsumerServiceIndex="0" AssertionConsumerServiceURL="https://localhost:5002/signin-spid" AttributeConsumingServiceIndex="0" xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol" >`

come riportato anche nella doc:

[https://www.agid.gov.it/sites/default/files/repository_files/circolari/spid-regole_tecniche_v1.pdf](url)

![image](https://user-images.githubusercontent.com/17255890/146182718-86e302cb-e915-41fa-a26c-64af3f5e0edf.png)

inoltre la proprietà ProtocolBinding della classe AuthnRequestType non è mai stata usata, quindi non potrebbe mai essere presente nell'Xml della request.

**Comment by danielegiallonardo** [comment]
Come riportato nel README:
"I valori di AssertionConsumerServiceIndex e AssertionConsumerServiceURL sono mutuamente esclusivi, è possibile indicare l'uno o l'altro, ma l'indicazione di entrambi causa la restituzione del codice di errore n.16 da parte dell'IdentityProvider."

**Comment by pampua84** [comment]
Però non è possibile specificare l'attributo ProtocolBinding nel caso uno scelga l'opzione consigliata, o mi sbaglio?

Riporto la parte di codice di interesse:

```
public static AuthnRequestType GetAuthnRequest(string requestId,
            string entityId,
            string assertionConsumerServiceURL,
            ushort? assertionConsumerServiceIndex,
            ushort attributeConsumingServiceIndex,
            X509Certificate2 certificate,
            IdentityProvider identityProvider)
        {

            BusinessValidation.Argument(requestId, string.Format(ErrorLocalization.ParameterCantNullOrEmpty, nameof(requestId)));
            BusinessValidation.Argument(certificate, string.Format(ErrorLocalization.ParameterCantNull, nameof(certificate)));
            BusinessValidation.Argument(identityProvider, string.Format(ErrorLocalization.ParameterCantNull, nameof(identityProvider)));
            BusinessValidation.ValidationCondition(() => string.IsNullOrWhiteSpace(identityProvider.SingleSignOnServiceUrl), ErrorLocalization.SingleSignOnUrlRequired);

            if (string.IsNullOrWhiteSpace(identityProvider.DateTimeFormat))
            {
                identityProvider.DateTimeFormat = SamlDefaultSettings.DateTimeFormat;
            }

            if (identityProvider.NowDelta == null)
            {
                identityProvider.NowDelta = SamlDefaultSettings.NowDelta;
            }

            string dateTimeFormat = identityProvider.DateTimeFormat;
            double nowDelta = identityProvider.NowDelta.Value;

            DateTimeOffset now = DateTimeOffset.UtcNow;

            return new AuthnRequestType
            {
                ID = "_" + requestId,
                Version = SamlConst.Version,
                IssueInstant = now.AddMinutes(nowDelta).ToString(dateTimeFormat),
                Destination = identityProvider.SingleSignOnServiceUrl,
                ForceAuthn = true,
                ForceAuthnSpecified = true,
                Issuer = new NameIDType
                {
                    Value = entityId.Trim(),
                    Format = SamlConst.IssuerFormat,
                    NameQualifier = entityId
                },
                AssertionConsumerServiceURL= assertionConsumerServiceURL,
                AssertionConsumerServiceIndex = assertionConsumerServiceIndex ?? SamlDefaultSettings.AssertionConsumerServiceIndex,
                AssertionConsumerServiceIndexSpecified = assertionConsumerServiceIndex.HasValue,
                AttributeConsumingServiceIndex = attributeConsumingServiceIndex,
                AttributeConsumingServiceIndexSpecified = true,
                NameIDPolicy = new NameIDPolicyType
                {
                    Format = SamlConst.NameIDPolicyFormat,
                    AllowCreate = false,
                    AllowCreateSpecified = false
                },
                Conditions = new ConditionsType
                {
                    NotBefore = now.ToString(dateTimeFormat),
                    NotBeforeSpecified = true,
                    NotOnOrAfter = now.AddMinutes(10).ToString(dateTimeFormat),
                    NotOnOrAfterSpecified = true
                },
                RequestedAuthnContext = new RequestedAuthnContextType
                {
                    Comparison = AuthnContextComparisonType.minimum,
                    ComparisonSpecified = true,
                    Items = new string[1]
                    {
                        SamlConst.SpidL + identityProvider.SecurityLevel
                    },
                    ItemsElementName = new ItemsChoiceType7[1]
                    {
                        ItemsChoiceType7.AuthnContextClassRef
                    }
                }
            };
        }
```

**Comment by danielegiallonardo** [comment]
Esatto, perchè lo standard SAML prevede il campo ProtocolBinding ma le specifiche SPID non lo prevedono come obbligatorio. Per SPID è sufficiente utilizzare il campo AssertionConsumerServiceIndex o, in alternativa, AssertionConsumerServiceURL.
Se è necessario, per qualche scenario documentato, dare la possibilità di impostare il campo ProtocolBinding, si può eventualmente pensare di introdurlo in configurazione, altrimenti non ne vedo la necessità.

**Comment by pampua84** [comment]
Quindi nel caso si voglia utilizzare l'attributo AssertionConsumerServiceURL non è obbligatorio anche l'utilizzo dell'attributo ProtocolBinding?

**Comment by danielegiallonardo** [comment]
No, mi risulta che AssertionConsumerServiceURL da solo sia sufficiente. Ma consiglio l'utilizzo di AssertionConsumerServiceIndex comunque.

**Comment by pampua84** [comment]
OK grazie mille
