### ISSUE TITLE
Personalizzazione attributo Destination nella AuthnRequest

### ISSUE THREAD

**Issue by pampua84** [italia/spid-aspnetcore#33]
Ciao,
sarebbe una buona feature poter personalizzare l'attributo Destination dell AuthnRequest con un valore diverso dal valore SingleSignOnServiceUrl, come viene fatto nel codice:

```
return new AuthnRequestType
{
    ID = "_" + requestId,
    Version = SamlConst.Version,
    IssueInstant = now.AddMinutes(nowDelta).ToString(dateTimeFormat),
    Destination = identityProvider.SingleSignOnServiceUrl,
    ForceAuthn = true,
    ForceAuthnSpecified = true,
......
}
```
in quanto per SPID in precedenza veniva popolato con l'entityID dell'IdP come riporta il doc:

[https://www.agid.gov.it/sites/default/files/repository_files/spid-avviso-n11-regolamento_recante_le_regole_tecniche-_specifica_saml-attributo_destination.pdf](url)

anche se in contrasto con le specifiche SAML. 
Sembra che ancora oggi, dopo 3 anni, la maggior parte degli IdP si aspettino ancora il valore dell'entityID in tale attributo.
Grazie

**Comment by danielegiallonardo** [comment]
Salve,
nell'avviso 11 allegato è riportato:

"Per limitare l'impatto del conflitto sulle implementazioni, si richiede agli identity provider SPID di supportare l’attributo Destination come descritto in entrambe le definizioni."

Da installazioni della libreria presenti in ambienti di produzione posso confermare che tutti gli IdP funzionano correttamente con l'attuale valorizzazione dell'attributo Destination, per cui l'avviso 11 si può ritenere recepito dagli IdP.

**Comment by pampua84** [comment]
Ok grazie mille per la risposta.

PS:Nella documentazione specificherei che si può settare anche il "SecurityLevel" per gli IdP direttamente dal file di settings, come hai fatto nell'esempio con la login eIDAS.
Grazie ancora
