### ISSUE TITLE
 Logout e gestione errori

### ISSUE THREAD

**Issue by jump4** [italia/spid-aspnetcore#35]
Buongiorno,
sto provando ad utilizzare la libreria testandola con l’Idp Demo Spid.
Ho i seguenti dubbi:
    1 non mi è chiaro come poter far partire la LogoutRequest dalla mia pagina del service provider verso l’idp di demo spid e se questa funzionalità è presente all’interno della libreria tramite il richiamo di un metodo di un controller (quale?)
   2) tramite il demo spid è possibile far partire una richiesta di Logout simulata verso l’applicazione di test? Se sì come?
   3) Se provo ad inviare un login response con Demo Spid, il campo “Audience” risulta sempre vuoto e devo inserire ogni volta l’indirizzo del metadata della mia applicazione. Come mai, c’è qualcosa di sbagliato nella richiesta che devo controllare?
   4) in che modo è possibile catturare le eccezioni della libreria sulla validazione delle risposte ricevute, senza dover modificare il codice della libreria? Non ho trovato metodi sugli handler della mia applicazione che consentano di catturare queste eccezioni e gestire gli errori.

Grazie mille

**Comment by danielegiallonardo** [comment]
Salve,
1. nell'HomeController dell'esempio [1_SimpleSPWebApp](https://github.com/italia/spid-aspnetcore/tree/main/samples/1_SimpleSPWebApp) è presente una action per effettuare il SignOut
2. Non mi risulta si possa simulare un Logout da Demo Spid
3. Credo manchi un passaggio preliminare, che è quello di registrazione del metadata del SP (che deve essere pubblicamente raggiungibile su internet) prima di effettuare il check delle Response
4. Sul README c'è una sezione apposita
