### ISSUE TITLE
Dubbio sessione individuale

### ISSUE THREAD

**Issue by jump4** [italia/spid-aspnetcore#36]
Buonasera,
dopo aver letto la documentazione relativa alla gestione della sessione “individuale” non mi è chiara la seguente frase:

"…in particolare le sessioni individuali possono:
    non essere instaturate
    essere chiuse anche nel corso di validità della sessione di autenticazione che le ha originate (ovvero prima di una eventuale richiesta di Single Logout o della scadenza del timeout associato alla sessione di autenticazione"
quale attributo contiene la data di scadenza della sessione di autenticazione,
Response->SubjectConfirmationData->notOnOrAfterField ?

Da quanto ho capito, se l’utente è gia loggato con spid livello 1 e vuole loggarsi con spid livello 2 non deve essere fatta di nuovo l’autenticazione: come può l’utente in quel caso rifare l’accesso con spid livello 2 senza dover passare dalla pagina di login del service provider?(e quindi senza aver fatto il logout?)

Grazie per l’aiuto.

**Comment by danielegiallonardo** [comment]
Non mi risulta che l'utente, dopo una autenticazione di livello 1, possa fare un upgrade verso un livello più alto senza ri-effettuare l'autenticazione, anche perchè nel caso di livelli 2 e 3 non viene instaurata una sessione individuale, e viene richiesta la login dal IdentityProvider ad ogni Request.
Inoltre mi risulta che la risposta sia stata già fornita su forum italia:
https://forum.italia.it/t/dubbio-sessione-individuale/28647/4
