### ISSUE TITLE
.net 5+ migration

### ISSUE THREAD

**Issue by scm-dev-ag** [italia/spid-aspnetcore#38]
Buongiorno,
vorrei sapere se state già lavorando per un'eventuale migrazione della libreria al .net 5 e superiori.
Avete già un branch a riguardo?
Grazie mille per il supporto e per il vostro lavoro.

**Comment by danielegiallonardo** [comment]
Salve, 
la libreria è .netstandard2.0, per cui è perfettamente compatibile con .NET5 e superiori.
