### ISSUE TITLE
Exception: Signature non valida

### ISSUE THREAD

**Issue by marco-maroni-spot-software** [italia/spid-aspnetcore#39]
Salve,
sto eseguendo in locale ilprogramma di esempio e nel momento in cui faccio il Logout ricevo questa eccezione:

"Exception: Signature non valida"

Il flusso di login funziona correttamente, quale potrebbe essere il problema nel logout?

Queste la mie configurazioni:

appsettings.json
![image](https://user-images.githubusercontent.com/6230180/157838477-a7183edc-a1b4-4618-86dc-29ae994eb1d2.png)

startup.cs
![image](https://user-images.githubusercontent.com/6230180/157838522-6fe883d3-972d-48b0-b8b2-67b3b1cfbac9.png)

Grazie

**Comment by danielegiallonardo** [comment]
Salve, se stai effettuando un logout usando l'IdP di demo, è un problema noto, l'IdP di demo non restituisce le response di signout firmate, è stato anche aperto un bug sul loro repository.

**Comment by marco-maroni-spot-software** [comment]
Sì corretto, sto provando facendo il logout del IdP di demo. Ok allora attendiamo la risoluzione del bug.

Grazie mille
