### ISSUE TITLE
Certificati non trovati

### ISSUE THREAD

**Issue by dassocec** [italia/spid-aspnetcore#4]
Buongiorno,
sto facendo girare l'applicazione in locale ma mi viene restituito sempre l'errore che il parametro certificate non può essere null, anche se imposto nell' appsettings.json il percorso e la password del certificato; ho provato anche ad impostare le informazioni del certificato dallo store, ma sembra che l'applicazione non riesca a leggere i certificati sul pc.
Qualcuno che possa aiutarmi, per favore?

**Comment by danielegiallonardo** [comment]
Salve,
come è valorizzato il campo ""Source" della sezione "Certificate" del file appsettings.json? Per il caricamento da file dovrebbe essere impostato sul valore "File"

**Comment by dassocec** [comment]
Ho valorizzato con file il campo Source.
Nel campo Path ho inserito "E:\\Download\\spid\\cert\\certificato.pfx".

Nel caso in cui volessi utilizzare lo "store",
ho valorizzato così:
"Location": "LocalMachine",
        "Name": "My",
        "FindType": "pfx",
        "FindValue": "nome_certificato",
        "validOnly": false

**Comment by danielegiallonardo** [comment]
Il valore di "FindType" deve essere la label dell'enumerato X509FindType, come riportato in documentazione: https://docs.microsoft.com/it-it/dotnet/api/system.security.cryptography.x509certificates.x509findtype?view=net-5.0
Ne consegue che il valore di "FindValue" dipende dal valore di "FindType" utilizzato, ad esempio, nel caso in cui si scelga per "FindType" il valore "FindByThumbprint", il valore di "FindValue" corrisponderà al valore esadecimale del thumbprint del certificato così come riportato nello store.
Per quanto riguarda il caricamento da File, dovrebbe funzionare, prova a valorizzare con "File" il campo "Source", e occhio al case.

**Comment by dassocec** [comment]
Ok, grazie mille. Ho risolto con il certificato. 

Ora, continuando ad eseguire l'applicazione, mi restituisce la seguente eccezione sul program.cs:
"System.FormatException: 'Could not parse the JSON file.'
JsonReaderException: Expected depth to be zero at the end of the JSON payload. There is an open JSON object or array that should be closed. LineNumber: 179 | BytePositionInLine: 0."

PS: sempre nel appsettings.json, il campo "EntityID" come deve essere valorizzato?

**Comment by danielegiallonardo** [comment]
Verifica che l'appsettings.json sia formattato correttamente, probabilmente è saltata qualche parentesi durante l'edit.
E' l'entityID per SPID da utilizzare in fase di collaudo, di test, o in produzione, rappresenta univocamente il ServiceProvider (o l'Aggregato, nel caso di uno scenario di Aggregatori), ma per la sua corretta valorizzazione ti rimando alla documentazione tecnica di SPID.

**Comment by dassocec** [comment]
Perfetto, risolto.

Ho un paio di dubbi ancora: 
- il tasto "entra con spid" come fa a visualizzare dinamicamente i tasti relativi agli idp di sviluppo e validazione (locale e non)? 
ora mi visualizza solo quelli in produzione.
- nel metadata da fornire agli idp di test, il link del "singlelogoutservice" è "http://localhost:44369/signout-spid", giusto?

Grazie mille per la tua disponibilità.

**Comment by dassocec** [comment]
Gentilissimo, grazie.
