### ISSUE TITLE
Eccezioni non gestibili

### ISSUE THREAD

**Issue by grigliaman** [italia/spid-aspnetcore#40]
https://github.com/italia/spid-aspnetcore/blob/81fc61d81e4772a46780d19edb21994ff7fe5f71/src/SPID.AspNetCore.Authentication/SpidHandler.cs#L134

Riscontriamo diversi casi in cui la verifica del cookie fallisce mandando in errore il processo.
Tutavia, essendo però questo codice al di fuori del blocco try sottostante , non è possibile gestire queste eventuali eccezioni tramite l'evento HandleAuthenticationFailed.

Sarebbe possibile includere le righe in oggetto nel blocco try?

Grazie

**Comment by danielegiallonardo** [comment]
Duplicato di #37
