### ISSUE TITLE
System.NullReferenceException in HandleSecurityTokenCreatingContext

### ISSUE THREAD

**Issue by marco-maroni-spot-software** [italia/spid-aspnetcore#41]
Sto utilizzando la libreria in un classica applicazione MVC che oltre ad avere controller e viste ha anche api che vengono chiamate dal front-end (angular) via javascript. Le api stesse sono protette dall'autenticazione. Seguendo il flusso di login (per ora sto usando il provider spid demo) tutto sembra funzionare correttamente, ma se per qualche motivo ho nel browser cookie SPID sessione non validi (esempio riavvio il server) ottengo questa eccezzione

```
      Object reference not set to an instance of an object.
      System.NullReferenceException: Object reference not set to an instance of an object.
         at SPID.AspNetCore.Authentication.SpidHandler.EventsHandler.HandleSecurityTokenCreatingContext(HttpContext context, AuthenticationScheme scheme, SpidOptions options, IdentityProvider idp, AuthenticationProperties properties, String samlAuthnRequestId)
         at SPID.AspNetCore.Authentication.SpidHandler.HandleChallengeAsync(AuthenticationProperties properties)
         at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.ChallengeAsync(AuthenticationProperties properties)
         at Microsoft.AspNetCore.Authentication.AuthenticationService.ChallengeAsync(HttpContext context, String scheme, AuthenticationProperties properties)
         at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
```

È corretto, sto sbagliando qualcosa? Devo gestire in qualche modo questa eccezione ed interpretarla come una "utente non autenticato"?

**Comment by danielegiallonardo** [comment]
Sarebbe da capire se ci sono SpidEvents che sovrascrivono la configurazione di default per EntityId, Certificate, AssertionConsumerServiceURL o AssertionConsumerServiceIndex, e se in questo caso li imposta correttamente.
In alternativa è probabile che non venga correttamente selezionato l'idp, non trovando (probabilmente) sulla QueryString di challenge correttamente impostato il parametro "idpName".
Queste sono le prime cose che mi vengono in mente guardando il codice.

**Comment by marco-maroni-spot-software** [comment]
Purtroppo no, nessuna delle condizioni che hai menzionato è il mio caso, non ho customizzato l'evento TokenCreating e nel momento in cui ricevo l'eccezione non è durante la login, ma quando quando chiamo un API e nel contesto ho cookie di sessione (che mi erano stati creati durante la login con successo) non più validi o assenti (perché proprio non ho ancora fatto login).
La sequenza con cui riesco facilmente a riprodure il problema è chiamando una api, protateta da autenticazione, da Postman per esempio senza impostare cookie, in questo caso mi aspeterei una sorta di 401, invece si genera sistematicamente quella eccezione.

**Comment by marco-maroni-spot-software** [comment]
@danielegiallonardo  ho un ulteriore elementi di indagine, andando in debug ho visto che il problema è causato dal fatto che se io chiamo una mia api tipo user/me (protetta da autenticazione) scatta HandleChallengeAsync immagino, per verificare se c'è il cookie e quindi una sessione valida con un utente autenticato, ma non essendoci nessun parametro in query string ipdName poi l'oggetto idp è null e la successiva chiamata HandleSecurityTokenCreatingContext da l'eccezione.

![image](https://github.com/italia/spid-aspnetcore/assets/6230180/31f7a5c3-6296-4eba-90b8-4a358e7ccb19)

Del resto questa è una richiesta di verifica del cookie legittama ma che non scatta da una login e quind non da una chiamata con in query string l'idp selezionato.

**Comment by danielegiallonardo** [comment]
La libreria non può essere utilizzata per l'autenticazione di API, ma solo per autenticazione ASP.NET web. L'authentication scheme di spid non dovrebbe essere quello di default, ma richiamabile esplicitamente dalla Challenge.

**Comment by marco-maroni-spot-software** [comment]
Ok grazie, direi che possiamo allora chiudere la issue.
