### ISSUE TITLE
Conformità ad "Avviso SPID n.19 versione 4" attributo "spid:entityType="spid:aggregator">"

### ISSUE THREAD

**Issue by marco-maroni-spot-software** [italia/spid-aspnetcore#42]
Durante la cerficicazione ci è stato sollevata l'eccezione della mancata presenza di questo attributo del tag ContactPerson nel metadata generato come service provider:

![image](https://user-images.githubusercontent.com/6230180/176861427-08c30e9e-3594-4f26-9d3a-79b9728d0f66.png)

Ma la libreria non lo genera o non vedo opzioni per generarlo.

Grazie

**Comment by danielegiallonardo** [comment]
Per generare un metadata come aggregatore/aggregato, è necessario usare uno dei seguenti tipi:

- ServiceProviderPublicFullAggregator
- ServiceProviderPrivateFullAggregator
- ServiceProviderPublicLightAggregator
- ServiceProviderPrivateLightAggregator

I tipi come semplici ServiceProvider Public o Private non generano questi tag.

**Comment by marco-maroni-spot-software** [comment]
Grazie sì corretto mi era sfuggita quella parte di documentazione.

**Comment by danielegiallonardo** [comment]
Nel tipo ServiceProviderPublicFullAggregator ci sono sia i campi AggregatorFiscalCode che AggregatedFiscalCode

**Comment by marco-maroni-spot-software** [comment]
Scusami mi sono sbagliato intendevo ServiceProviderPublicFullOperator ("pub-op-full")

**Comment by danielegiallonardo** [comment]
Pubblicato package versione 1.3.12 contenente il fix

**Comment by danielegiallonardo** [comment]
Si, è corretto, perchè nel caso degli aggregatori o degli operatori, l'entityId viene composto in automatico dalla libreria come composizione di 3 diversi parametri, mentre nel caso di SP pubblico o privato, lascio la scelta all'utilizzatore della libreria. Mi rendo conto che è un po' fuorviante, aggiornerò la documentazione. Nel frattempo comunque puoi tranquillamente utilizzare la versione 1.3.12 valorizzando opportunamente i campi nel caso di Operator (senza https)

**Comment by marco-maroni-spot-software** [comment]
Ok sì sono obbligato a fare una cosa del genere, non bellssimo ma sembra funzionare.
![image](https://user-images.githubusercontent.com/6230180/177108450-67d70a83-2069-464c-acac-6fc8fb6412ad.png)
