### ISSUE TITLE
OpenID Connect

### ISSUE THREAD

**Issue by cicognani71** [italia/spid-aspnetcore#43]
Buonasera, è stato realizzato l'aggiornamento della libreria per OIDC?
Grazie
Saluti

**Comment by danielegiallonardo** [comment]
Salve, si, è presente una prima versione al seguente repository: https://github.com/italia/spid-cie-oidc-aspnetcore

**Comment by cicognani71** [comment]
Buongiorno, grazie della risposta.
Due domande:
1) la nuova versione postata coesiste con la libreria SPID o è sostitutiva?
2) quando contate di rilasciare la Versione 1.0.0?
Grazie
Saluti

Il giorno lun 25 lug 2022 alle ore 18:58 Daniele Giallonardo <
***@***.***> ha scritto:

**Comment by danielegiallonardo** [comment]
Attualmente la versione OIDC è in fase di sviluppo, anche da parte degli IdentityProvider, e che io sappia non esiste ancora una procedura di onboarding e collaudo per la versione OIDC, quindi l'unica versione attualmente funzionante in ambiente di produzione è quella legacy SAML2. Purtroppo non sono a conoscenza di una roadmap di rilascio della versione OIDC, mi spiace.
