### ISSUE TITLE
SPID.AspNetCore.IdentityServerSample error

### ISSUE THREAD

**Issue by mikeflower** [italia/spid-aspnetcore#45]
Ciao,
prima di tutto complimenti per l'implementazione.

Sto sicuramente sbagliando qualcosa perchè non riesco ad eseguire nessun test, ricevo sempre errori
Ho scaricato il progetto ed ho eseguito la solution SPID.AspNetCore.IdentityServerSample senza modificare nulla dei progetti,  selezionado il provider

- **Poste** mi restituisce: 
Formato richiesta non corretto - Contattare il gestore del servizio

- Selezionando **Aruba** mi restituisce:

An unhandled exception occurred while processing the request.
Exception: Formato della richiesta non conforme alle specifiche SAML

SPID.AspNetCore.Authentication.Saml.SamlHandler.ValidateAuthnResponse(ResponseType response, AuthnRequestType request, EntityDescriptorType metadataIdp, string serializedResponse)
Exception: An error was encountered while handling the remote login.

Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler<TOptions>.HandleRequestAsync()

- Selezionando **Intesa**: mi porta alla pagina dove mi propone la registrazione o annulla

selezionanado: **demo.spid.gov** ed eseuendo l'invio a provider mi viene restituito 
An unhandled exception occurred while processing the request.
Exception: Audience non specificato

SPID.AspNetCore.Authentication.Helpers.BusinessValidation.ValidationNotNullNotWhitespace(string input, string nameVariable)
Exception: An error was encountered while handling the remote login.

Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler<TOptions>.HandleRequestAsync()

- Selezionando **InfoCert**:

ERRORE SULLA VERIFICA DELLA FIRMA DELLA RICHIESTA

Formato richiesta non corretto - Contattare il gestore del servizio

CODICE ERRORE:null

**_Vi ringrazio anticipatamente per gli eventuali chiarimenti che mi darete.
Saluti_**

**Comment by danielegiallonardo** [comment]
Salve, non è possibile effettuare i test di integrazione con gli IdentityProvider di produzione, la login con questi IdP funziona solo dopo la procedura di collaudo con Agid e dopo aver sottoscritto la convenzione ed inviato i metadata. In fase di integrazione è necessario usare altri tool di sviluppo, come ad esempio l'IdP di test https://demo.spid.gov.it/
Qui sono spiegate le procedure tecniche e amministrative: https://www.spid.gov.it/cos-e-spid/diventa-fornitore-di-servizi/
