### ISSUE TITLE
"Errore 16 - AssertionConsumerService non correttamente valorizzato" su implmentazione in produzione con collaudo approvato

### ISSUE THREAD

**Issue by marco-maroni-spot-software** [italia/spid-aspnetcore#46]
Siamo in produzione con lo SPID e la convezione approvati e colluadi passati, ma ad oggi dopo 20 giorni dalla fine del procedimento tecnico e amministrativo, provando ad accedere da qualsiasi IdP otteniamo sempre il seguente errore:

"AssertionConsumerService non correttamente valorizzato"

La richiesta che viene inoltrata dalla libreria è la seguente

```
<?xml version="1.0" encoding="utf-16"?>
<AuthnRequest
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema" ID="_b3df5cad-9adc-4970-ba2c-ac7cf6205284" Version="2.0" IssueInstant="2022-08-26T09:52:48.937723Z" Destination="https://identity.sieltecloud.it/simplesaml/saml2/idp/SSO.php" ForceAuthn="true" AssertionConsumerServiceIndex="0" AssertionConsumerServiceURL="https://sportellovirtuale.bonificaromagna.it/signin-spid" AttributeConsumingServiceIndex="0"
	xmlns="urn:oasis:names:tc:SAML:2.0:protocol">
	<Issuer NameQualifier="https://sportellovirtuale.bonificaromagna.it/pub-op-full/" Format="urn:oasis:names:tc:SAML:2.0:nameid-format:entity"
		xmlns="urn:oasis:names:tc:SAML:2.0:assertion">https://sportellovirtuale.bonificaromagna.it/pub-op-full/
	</Issuer>
	<NameIDPolicy Format="urn:oasis:names:tc:SAML:2.0:nameid-format:transient" />
	<Conditions NotBefore="2022-08-26T09:42:48.937723Z" NotOnOrAfter="2022-08-26T10:02:48.937723Z"
		xmlns="urn:oasis:names:tc:SAML:2.0:assertion" />
		<RequestedAuthnContext Comparison="minimum">
			<AuthnContextClassRef
				xmlns="urn:oasis:names:tc:SAML:2.0:assertion">https://www.spid.gov.it/SpidL2
			</AuthnContextClassRef>
		</RequestedAuthnContext>
	</AuthnRequest>
```

ed in effetti si nota che non è conforme con questa affermazione del documento che descrive i vari errori, nel nostro caso il 16

> AssertionConsumerServiceIndex riportato in presenza di uno od entrambi gli attributi AssertionConsumerServiceURL e ProtocolBinding

Nella richiesta inviata dalla libreria in effetti oltre ad AssertionConsumerServiceIndex è specificato anche l'URL? Potrebbe essere questo il problema? Se sì la domanda sucessiva è come è possibile che fase di collaudo questo problema non sia emerso?

Potrebbe essere questo un errore fuorviante, che nasconde invece il fatto che il metadata non è stato inviato correttamente agli identity provider?

Grazie

**Comment by danielegiallonardo** [comment]
Come da regole spid, URL e Index sono mutuamente esclusivi nella request, per cui se si specifica l'uno non bisogna specificare l'altro. Uno dei due va eliminato (e.g. impostato a null), personalmente uso l'index, ma è possibile scegliere.

**Comment by marco-maroni-spot-software** [comment]
Ok ma quel messaggio viene composto dalla libreria, io non ho modo di customizzarlo, sbaglio?

Ho verificato ed in fase di collaudo il messaggio era formattato nello stesso ed è passato ,come possibile se è questo il problema?

**Comment by danielegiallonardo** [comment]
Si, il messaggio sta nelle resources della libreria ed è conforme alle linee guida per quanto riguarda l'errore 16. Non so perché in fase di collaudo non sia venuto fuori, ma è corretto che in caso di valorizzazione di entrambi i campi gli IdP di produzione restituiscano l'errore 16. Uno dei due campi va rimosso, come riportato anche dal README.

**Comment by marco-maroni-spot-software** [comment]
Grazie mille, si era quello il problema mi era sfuggito in fase di configurazione, ma oggettivamente molto molto strano che non sia emerso in fase di collaudo!! 🤷‍♂️
