### ISSUE TITLE
SielteID doesn't work: Error Code 16

### ISSUE THREAD

**Issue by mrossini109** [italia/spid-aspnetcore#47]
Buongiorno,

non riusciamo ad accedere al provider SielteID. 

![sielte_error](https://user-images.githubusercontent.com/10862548/192744670-408ab9b0-f250-41e9-9f16-d266ac058947.PNG)

I parametri di configurazione del provider sono i seguenti;

> {
        "Name": "Sielte",
        "OrganizationName": "Sielte S.p.A.",
        "OrganizationDisplayName": "Sielte S.p.A.",
        "OrganizationUrlMetadata": "https://identity.sieltecloud.it/simplesaml/metadata.xml",
        "OrganizationUrl": "http://www.sielte.it",
        "OrganizationLogoUrl": "https://raw.githubusercontent.com/italia/spid-sp-access-button/master/src/production/img/spid-idp-sielteid.svg",
        "SingleSignOnServiceUrl": "https://identity.sieltecloud.it/simplesaml/saml2/idp/SSO.php",
        "SingleSignOutServiceUrl": "https://identity.sieltecloud.it/simplesaml/saml2/idp/SLO.php",
        "Method": "Post",
        "Type": "IdentityProvider",
        "NowDelta": -2
      },

Il manifest che generiamo (già validato dall' Agenzia) è disponibile a questo indirizzo: https://asstval-portalecittadino.azurewebsites.net/metadata-spid/metadata.xml

Sottolineo che lo stesso **funziona con tutti gli altri providers**. 

E' possibile che ci sia qualche aggiornamento del provider che manca? Possiamo intervenire in qualche modo?

Grazie,
M.

**Comment by danielegiallonardo** [comment]
Salve,
se con tutti gli altri provider funziona è possibile che il metadata non sia stato recepito da Sielte. Dovreste verificare con AGID se è questo il caso.

**Comment by mrossini109** [comment]
Ciao Daniele,

(con i tempi biblici di Agid/Sielte) abbiamo fatto una verifica.

Sielte lamenta il fatto che nella richiesta SAML siano presenti sia AssertionConsumerServiceIndex che 
AssertionConsumerServiceURL. Sembra che tutti gli altri provider accettino anche il valore "" mentre per loro (solo per loro, ripeto) non dovrebbe esserci proprio.

Questo è uno stralcio della richiesta SAML:

`<samlp:AuthnRequest xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion"
                    xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol"
                    ID="_05778142-0231-45bd-ad2a-ef44034aa741"
                    Version="2.0"
                    IssueInstant="2022-11-11T17:12:25.921319Z"
                    Destination="https://identity.sieltecloud.it/simplesaml/saml2/idp/SSO.php"
                    ForceAuthn="true"
                    AssertionConsumerServiceIndex="0"
                    AssertionConsumerServiceURL=""
                    AttributeConsumingServiceIndex="0"`

E' possibile a tuo avviso evitare di mandare quel campo se nelle config è settato come:

"AssertionConsumerServiceURL": null

?

Grazie, Marco.

**Comment by danielegiallonardo** [comment]
Salve Marco,
è molto strano quello che mi dici perchè mi risulta che la libreria non invii affatto l'attributo AssertionConsumerServiceURL nel caso in cui questo sia impostato a null da configurazione.
Ho appena provato su una mia installazione sulla quale valorizzo esclusivamente l'attributo AttributeConsumingServiceIndex e posso confermarti che la libreria non invia AssertionConsumerServiceURL, difatti con Sielte mi compare correttamente la pagina di login. 
Prova a verificare che usi l'ultima versione disponibile della libreria e che in nessuna parte del codice (o della config) venga valorizzato il parametro di configurazione AssertionConsumerServiceURL.

**Comment by danielegiallonardo** [comment]
Chiudo per inattività
