### ISSUE TITLE
attributi user.identity

### ISSUE THREAD

**Issue by dassocec** [italia/spid-aspnetcore#5]
Nel LoggedIn.cshtml, come fare a visualizzare altre informazioni dell'utente, come Nome, Cognome, CodiceFiscale, ecc. oltre all'email? 
Vorrei visualizzare gli attributi dell'AttributeConsumingService nel metadata.

Sono solo riuscito a modificare nel SpidHandler.cs alla riga 365, al posto di "email" passo il "name" e visualizzo solo il nome dell'utente nella pagina di loggedIn.

**Comment by danielegiallonardo** [comment]
Salve.
Non è necessario modificare il codice della libreria. 
Come riportato nella documentazione, gli attibuti restituiti da Spid sono disponibili, dopo l'autenticazione, come claims all'interno del ClaimsPrincipal (HttpContext.User), ed accessibili così:

```csharp
        var name = principal.FindFirst(SpidClaimTypes.Name);
        var surname = principal.FindFirst(SpidClaimTypes.Surname);
        var email = principal.FindFirst(SpidClaimTypes.Email);
        var fiscalCode = principal.FindFirst(SpidClaimTypes.FiscalNumber);
        // etc....
```
dove `principal` corrisponde a `HttpContext.User`.

**Comment by dassocec** [comment]
Perdona l'ignoranza, ma non riuscendo a leggere la documentazione, come faccio a richiamare queste variabili nella pagina loggedin.cshtml?

**Comment by danielegiallonardo** [comment]
Puoi trovare la documentazione nel README nella pagina principale di questo repository.
Ad ogni modo nei .cshtml è presente l'oggetto "User" che rappresenta il ClaimsPrincipal dell'utente autenticato.
Puoi accedere ai vari claims semplicemente scrivendo, ad esempio per prendere il claim Name, `User.FindFirst(SpidClaimTypes.Name)`

**Comment by dassocec** [comment]
Usando _User.FindFirst(SpidClaimTypes.Name)_ il compilatore mi dice: "CS0103: il nome 'SpidClaimTypes' non esiste nel contesto corrente"

**Comment by danielegiallonardo** [comment]
Devi aggiungere lo using in testa al file
`@using SPID.AspNetCore.Authentication.Models`

**Comment by dassocec** [comment]
Quindi l'override delle variabili (come da documentazione) bisogna farlo nello startup.cs ?

Ok, risolto per la visualizzazione degli attributi, ma se volessi visualizzare solo i dati, senza l'etichetta davanti? 
_FamilyName_: Orlando
_Email_: silvestriquarto@libero.it
_FiscalNumber_: RLNMRO90T26C520N

Praticamente dovrei passare tali dati in un link ad un'interfaccia web...

**Comment by danielegiallonardo** [comment]
L'override puoi farlo da appsettings.json o da startup.cs.
Nei claims sono presenti già i valori, ti basta fare `User.FindFirst(SpidClaimTypes.Name)?.Value`
Chiudo, perchè la issue è risolta

**Comment by dassocec** [comment]
Ti ringrazio moltissimo per i chiarimenti e scusa la banalità delle domande, ma sono un neofita in questo ambiente.
