### ISSUE TITLE
Richiesta informazione

### ISSUE THREAD

**Issue by RossiNIT** [italia/spid-aspnetcore#50]
Analizzando la libreria non ho capito in che modo venga deciso quale livello di SPID request effettuare (livello 1, 2 o 3). E' possibile sceglierlo o impostarlo da codice?

**Comment by danielegiallonardo** [comment]
Salve,
per ogni IdentityProvider è possibile impostare il parametro "SecurityLevel" con uno tra i 3 valori previsti (1, 2, 3). Il default è 2.
In questo modo ogni request creata relativamente a questo IdP sarà al livello configurato.
In alternativa, è possibile intercettare l'evento OnRedirectToIdentityProvider degli SpidEvents, e impostare il livello sul IdP per-request.
