### ISSUE TITLE
Error code delle exception

### ISSUE THREAD

**Issue by RossiNIT** [italia/spid-aspnetcore#51]
E' possibile ottenere lato applicazione, il codice d'errore (ErrorCode, secondo la Tabella messaggi di anomalia fornita da AGID) delle varie eccezioni generate dalla libreria di atenticazione, per poi stamparle sulla pagina error.cshtml?

**Comment by danielegiallonardo** [comment]
Ogni codice di errore, come da linee guida SPID, è stato localizzato con il corrispondente messaggio. Si è deciso di non lasciare l'onere della localizzazione all'utilizzatore della libreria per facilitare le operazioni di collaudo. Sono aperto a PR comunque :-)
