### ISSUE TITLE
Usando qualsiasi operatore (Poste.it, Aruba, etc) si ottiene "Errore: Formato richiesta non corretto - Contattare il gestore del servizio"

### ISSUE THREAD

**Issue by elcar75** [italia/spid-aspnetcore#52]
Buongiorno,
Sto provando l'applicazione di esempio spid-aspnetcore-main\samples\1_SimpleSPWebApp

Quando scelgo un "operatore" (Poste.it, Aruba, etc) ottengo il messaggio 

<<Errore:
Formato richiesta non corretto - Contattare il gestore del servizio>>

Probabilmente non ho configurato qualcosa.
E' possibile avere assistenza?

Premetto che la demo è lanciata in debug in locale in Visual Studio sul mio PC.
Ipotizzo che probabilmente, l'operatore selezionato, tenta una callback verso l'applicazione, ma essendo che questa non è esposta su internet, non è raggiungibile. Può essere questa la ragione dell'errore?

Sono un utente di SPID in quanto possessore di credenziali personali su Poste.it, ma ammetto di essere molto ignorante in materia di SPID come developer.
Vi sarei grato se poteste fornirmi supporto.

Grazie 
Elio Carretta

<img width="586" alt="image" src="https://user-images.githubusercontent.com/123069461/213414657-f59c2f5d-194b-4211-a19b-dc6aaac76610.png">

**Comment by danielegiallonardo** [comment]
Salve,
non è possibile utilizzare i provider di produzione con il metadata di test, per farlo è necessario superare le fasi di collaudo e accreditamento come SP (o come aggregatore).
Ai fini di test è possibile utilizzare esclusivamente i provider demo.

**Comment by danielegiallonardo** [comment]
Si esatto, bisogna prima diventare fornitore di servizi come indicato a questa guida: https://www.spid.gov.it/cos-e-spid/diventa-fornitore-di-servizi/
Saluti
