### ISSUE TITLE
Scelta del metadata

### ISSUE THREAD

**Issue by RossiNIT** [italia/spid-aspnetcore#53]
In che modo all'interno della web app io posso scegliere quale metadata caricare, senza sovrascrivere il file volta per volta

**Comment by danielegiallonardo** [comment]
Di quale metadata si parla?

**Comment by RossiNIT** [comment]
Sto parlando del **metadata** del **service provider**, quello presente nella cartella _wwwroot/spid/metadata.xml_.
La domanda è: posso avere due metadata (ad esempio uno _metadata.xml_ e uno _development_metadata.xml_) e lato codice decidere esecuzione per esecuzione quale scegliere in base a dei criteri?

**Comment by danielegiallonardo** [comment]
Certo, è possibile avere un numero arbitrario di metadata da esporre, e costruire la request a runtime usando gli SpidEvents
