### ISSUE TITLE
Log su storage esterno

### ISSUE THREAD

**Issue by dassocec** [italia/spid-aspnetcore#54]
Buongiorno,
sto implementando nello startup.cs (nella public class CustomSpidEvents : SpidEvents) il log degli accessi su storage esterno, come suggerito nel manuale di utilizzo.
Nello specifico, nel comando "await _fileStorage.UploadFileAsync("spid", $"{id}_Response", stream, "application/xml", $"{id}_Response");"
_fileStorage è una classe? 
UploadFileAsync è un metodo di questa classe? 
Si può avere un esempio di come strutturare la funzione? 

Grazie.

**Comment by danielegiallonardo** [comment]
Salve,
il compito di come e dove salvare i file di Log è lasciato all'utilizzatore, quel metodo "UploadFileAsync" è solo un esempio, non è una classe disponibile all'interno della libreria.
E' possibile utilizzare qualsivoglia tecnologia di storage, dal FileSystem, ad un cloud storage, o a db SQL/NoSQL, ma l'implementazione della scrittura del Log è lasciata a chi utilizza la libreria.
