### ISSUE TITLE
Aggiornamento automatico degli IdP

### ISSUE THREAD

**Issue by marco-maroni-spot-software** [italia/spid-aspnetcore#56]
Alla luce dell' [avviso n.42](https://www.agid.gov.it/sites/default/files/repository_files/spid-avviso-n42-spid_bottone.pdf) della AGID , in merito alla necessità di implementare l'aggiornamento automatico della lista degli IdP, sarebbe molto utile che la libreria si adeguasse permettendo che la configurazione si generasse automaticamente dalal risposta del servizio menzionato nell'avviso. Evitando quindi di doverne mantenere la configurazione per le app che usano la libreria, con tutti i benefici del caso.

**Comment by danielegiallonardo** [comment]
Creata versione 2.0.0 del package contenente questa feature.
