### ISSUE TITLE
Eccezione non gestita. Certificato registry spid scaduto

### ISSUE THREAD

**Issue by stefanonucida** [italia/spid-aspnetcore#59]
Buongiorno, in data odierna il certificato risulta essere scaduto. 
In fase di creazione del button "entra con spid" della libreria 2.0.0 il sistema va in eccezione, dunque la lista di IDP non viene popolata.
Se dovesse servirvi ho già fixato il codice nel mio fork in locale.
![spid-cert-fail](https://github.com/italia/spid-aspnetcore/assets/63106865/7c74da02-dfca-497a-b6ac-8e374a78963e)

**Comment by danielegiallonardo** [comment]
Salve, fermo restando che è una situazione che andrebbe risolta dal registry spid, in cosa consiste il fix?

**Comment by stefanonucida** [comment]
sicuramente la scadenza del certificato è da gestire (e difatti il problema è stato risolto). ma vedendo che viene utilizzato let's encrypt per il certificato e data la durata relativamente breve del certificato in questione presumo che questa non è stata la prima volta in cui il servizio non ha funzionato e ne sarà l'ultima, pertanto nella classe SpidOptions.cs nel blocco try finally  del metodo GetIdentityProviders, nel mio caso ho aggiunto un catch per garantire che il button venga correttamente creato (e nel caso in cui mi trovo al momento) con gli IDP di demo.

**Comment by danielegiallonardo** [comment]
Si ok, ma il catch, nel caso in cui la call verso il registry fallisca per il fallito handshake SSL, cosa fa per garantire la creazione del button? Lo crea semplicemente vuoto, senza la lista di IdP?

**Comment by stefanonucida** [comment]
Lo crea con la lista degli IdP presenti nel file di appsettings (che sono poi quelli di demo e validazione).

**Comment by danielegiallonardo** [comment]
In questo modo però ingoierebbe l'eccezione, e non ci sarebbe modo di capire per quale motivo è fallita la valorizzazione della lista degli IdP

**Comment by stefanonucida** [comment]
ok, se non ritenete opportuno modificare il codice potete chiudere la issue, io ho fixato il mio codice in locale per garantire l'accesso agli idp recuperati da appsettings anche nel caso di fails del registry quindi per me è ok. grazie e buon lavoro

**Comment by danielegiallonardo** [comment]
In generale non credo sia una buona idea effettuare swallowing di una eccezione e non fornire riscontro a chi utilizza la libreria. E' possibile tuttavia gestire l'errore opportunamente tramite l'ErrorHandler, al fine di mostrare un messaggio d'errore all'utente.
Chiudo, grazie comunque per la segnalazione

**Comment by stefanonucida** [comment]
buongiorno, in data odierna l'url utilizzato dal button ha problemi. 
https://registry.spid.gov.it/entities-idp?&output=json
![spid_registry](https://github.com/italia/spid-aspnetcore/assets/63106865/34d0753b-d739-4005-a224-1d98426f7dc2)
avendo seguito il vostro consiglio di non occultare l'errore abbiamo gestito il FE per segnalare l'accaduto.
Tuttavia il nuovo approccio di "dinamicità" sul fetch degli idp è già al secondo malfunzionamento (a causa del registry, sia chiaro). E' plausibile la parametrizzazione della sorgente di informazioni così da poter usare la nuova libreria ma con il vecchio approccio con il caricamento degli appsettings? Grazie

**Comment by stefanonucida** [comment]
non ho capito la risposta. la PR linkata non effettua fallback su appsettings. inoltre come da avviso 42 sembra che effettivamente la lista idp debba essere necessariamente fetchata dal registry, tuttavia il servizio funziona a singhiozzo.
https://www.agid.gov.it/sites/default/files/repository_files/spid-avviso-n42-spid_bottone.pdf
