### ISSUE TITLE
La chiave privata del certificato non è presente

### ISSUE THREAD

**Issue by mperu92** [italia/spid-aspnetcore#6]
Buongiorno, 
sto provando ad effettuare i primi accessi con SPID.
Ho usato `openssl` per creare il certificato `.pfx`, lanciando i seguenti comandi:

`openssl req -newkey rsa:2048 -nodes -keyout mycompany_spid_privatekey.pem -x509 -days 365 -out mycompany_spid_certificate.pem`

`openssl pkcs12 -export -in mycompany_spid_certificate.pem -inkey mycompany_spid_privatekey.pem -out mycompany_spid_certificate.pfx`
che ho trovato nell'altra repository [spid-dotnet-sdk]( https://github.com/italia/spid-dotnet-sdk).

Una volta generato il file `.pfx`, ho eseguito il wizard di Windows per installarlo nella macchina locale, in `Trusted People` per l'esattezza.
Una volta fatto questo, dalla gestione certificati computer, ho esportato il `.cer` in formato base64.
Ho scaricato il progetto di cui questa repository, e nell' `appsettings.json` nella sezione `Certificate` ho inserito le seguenti sezioni:
```js
    "Certificate": {
      "Source": "File",
      "Store": {
        "Location": "CurrentUser", // non sono bene sicuro di quale sia il valore corretto da inserire qui
        "Name": "My",  // non sono bene sicuro di quale sia il valore corretto da inserire qui
        "FindType": "FindBySubjectName",
        "FindValue": "MyCompany", // ho supposto che il value fosse il nome che nel dettaglio del certificato mostra come Issued By/Issued To ma non ne sono sicuro
        "validOnly": false
      },
      "File": {
        "Path": "C:\\Users\\dev\\Desktop\\spid-aspnetcore-main\\spid-aspnetcore-main\\SPID.AspNetCore.Authentication\\SPID.AspNetCore.WebApp\\mycompany_spid_certificate\\mycompany_spid_certificate.pfx",
        "Password": "pswrd"
      },
      "Raw": {
        "Certificate": "la stringa base64 ricavata dal .cer",
        "Password": "pswrd"
      }
    },
```

Una volta lanciata in locale l'app, quando chiedo di effettuare la login viene lanciata la seguente eccezzione:
> WindowsCryptographicException: Keyset does not exist
> System.Security.Cryptography.CngKey.Open(string keyName, CngProvider provider, CngKeyOpenOptions openOptions)
>
> FieldAccessException: La chiave privata del certificato non è presente
> SPID.AspNetCore.Authentication.Helpers.XmlHelpers.SignXMLDoc(XmlDocument doc, X509Certificate2 certificate, string referenceUri, string signatureMethod, string digestMethod) in XmlHelpers.cs, line 43

Anche mettendo `Raw` al posto di `File` ottengo la stessa eccezione.
A quanto pare il problema sembra essere la chiave del certificato, devo aver perso qualche passaggio ma non riesco a capire dove.
Dove sto sbagliando?

Grazie mille

**Comment by danielegiallonardo** [comment]
Ci sono diversi casi qui:
1. Nel caso in cui carichi il certificato dallo store, assicurati, in fase di importazione, che la chiave privata sia marcata come esportabile (ci dovrebbe essere un flag nella procedura) e che l'utente che sta eseguendo la webapp abbia i permessi per leggere la chiave privata.
2. In conseguenza del punto 1, se in fase di import non hai marcato la chiave privata come esportabile, se provi a esportare il certificato dallo store di Windows, non porterà con sè la chiave privata. Inoltre devi esportare il certificato come pfx, non come .cer (che invece contiene solo la chiave pubblica)
3. il Raw deve comunque contenere la chiave privata, per cui non puoi prendere la stringa base64 del file .cer. Per ottenere il base64 da un pfx puoi procedere in questo modo: in una ConsoleApp carichi il certificato da file pfx (contenente quindi la chiave privata) e poi lo esporti, con le seguenti istruzioni:

```csharp
var cert = new X509Certificate2("path-to/file.pfx", "password", X509KeyStorageFlags.MachineKeySet | X509KeyStorageFlags.PersistKeySet | X509KeyStorageFlags.Exportable);
var certByte = cert.Export(X509ContentType.Pfx, "newpassword");
var rawBase64 = Convert.ToBase64String(certByte);
```

In questo modo ottieni la stringa Raw Base64 che, congiuntamente con "newpassword" ti consente di caricare un certificato a runtime.

**Comment by mperu92** [comment]
Ho seguito gli step indicati.
Una volta reimportato il certificato nella macchina locale (marcando la chiave come esportabile), seguendo il percorso certificato -> all tasks -> mange private keys ho aggiunto il mio utente di dominio dandogli tutti i permessi.
Successivamente ho esportato il certificato.
Adesso, quando vado a richiamarlo (sia file che raw), comunque mi viene detto Access Denied, riesco ad eseguirlo solo se apro Visual Studio come Admin, altrimenti mi dice Access Denied.
Probabilmente continuo a non eseguire correttamente dei passaggi, ma comunque da Admin non mi viene detto Access Denied.

**Comment by danielegiallonardo** [comment]
Probabilmente ti conviene seguire lo step 3, esportare il certificato in rawbase64 e salvarlo altrove insieme alla sua password (e.g. keyvault, azure app configuration, appsettings, DB, ecc....), di modo tale che anche in ambienti che non siano specificamente la tua macchina la webapp continui a funzionare senza doverti preoccupare di dove e come installi il certificato e dell'utente che esegue l'applicazine

**Comment by danielegiallonardo** [comment]
Riesci a eseguirlo solo come Admin perchè hai importato il certificato in LocalMachine. Se l'avessi importato in CurrentUser non avresti avuto il problema.

**Comment by mperu92** [comment]
Ok, chiedo venia, solo per capire se ho capito bene perché questo passaggio più sistemistico mi confonde un poco:
una volta ottenuto il pfx con openssl, eseguo il wizard di import importando il certificato non in Local Machine ma in Current User (marcando la chiave come esportabile)
Una volta fatto lo esporto come pfx dal wizard, e successivamente lo passo nella ConsoleApp per generare la stringa base64.
Una volta ottenuta salvo la stringa e la password ad esempio nell'azure app configuration.
Questi dovrebbero essere i passaggi da eseguire?
Grazie mille

**Comment by danielegiallonardo** [comment]
No, non tutti necessariamente, dipende da quale approccio vuoi usare. Per ottenere il rawbase64 puoi anche semplicemente esportare (con quel codice che ti ho riportato sopra) direttamente a partire dal pfx generato con openssl. 
L'import nello store lo fai solo se devi/vuoi leggere i certificati da lì.

**Comment by mperu92** [comment]
Ok,
solo l'ultima cosa, se eseguo le linee di comando per esportare il rawbase64 usando quello creato da openssl mi dato il seguente errore "Keyset does not exist"
E' sintomo di una sbagliata creazione tramite openssl immagino?

**Comment by danielegiallonardo** [comment]
E' davvero strano, se crei l'oggetto X509Certificate2 a partire dal pfx con i X509KeyStorageFlags che ho indicato sopra, la chiave privata dovrebbe caricarla correttamente nell'oggetto e poi esportarla. Prova ad andare in debug e vedi se nell'oggetto X509Certificate2 è presente la property "PrivateKey"

**Comment by mperu92** [comment]
Rettifico, ho risolto aggiungendo X509KeyStorageFlags.UserKeySet al parametro KeyStorageFlag della classe X509Certificate2

**Comment by danielegiallonardo** [comment]
Ok, probabilmente stavi eseguendo VS non da Admin.

**Comment by mperu92** [comment]
Sì, in effetti è così. Ho dovuto aggiungere il flag X509KeyStorageFlags.UserKeySet anche nella web app quando richiama GetCertificateFromStrings. 
Infatti adesso lo runno correttamente senza dover aprire VS come Admin.
Ora sono in locale, ma queste configurazioni (con il rawbase64 e la pw salvate nell'app config di Azure) funzioneranno anche online?

**Comment by danielegiallonardo** [comment]
Se utilizzi la libreria nuget si.
Se utilizzi un fork modificato del codice non posso darti garanzie.
Chiudo la issue.

**Comment by mperu92** [comment]
Ok, perfetto grazie mille!
