### ISSUE TITLE
Messaggi di errore non conformi alle indicazioni di AgID

### ISSUE THREAD

**Issue by PiemP** [italia/spid-aspnetcore#67]
**Describe the bug**
settimana scorsa ho iniziato il processo di accreditamento a SPID come fornitore di servizi e ho ricevuto come risposta un report dove mi vengono segnalate diverse anomalie relative ai messaggi di errore restituiti dal mio applicativo. 

Siccome sfrutto le eccezioni generate dalla libreria in questione e i relativi messaggi credo che esista un problema di allineamento tra le risorse messe a disposizione dalla libreria e quanto richiesto da AgID.  

**Expected behavior**
Vorrei fare un PR per correggere i messaggi di errore e cogliere l'occasione per produrre un eccezione ad hoc per queste verifiche di modo che chiunque possa capire il codice del test a cui è legata la segnalazione ed eventualmente customizzare i propri messaggi di errore.

**Comment by danielegiallonardo** [comment]
Salve,
su quali messaggi hai riscontrato un disallineamento?

**Comment by PiemP** [comment]
Loro mi hanno segnalato il test 104 e 111 oltre ad altri test dove si attendono un messaggio di errore generico (su cui non ho idea se sia necessario un formato specifico) mentre la libreria ritorna un messaggio di errore relativo all'anomalia riscontrata (tipo per il test 2 vogliono un messaggio di errore generico mentre la libreria ritorna `Signature Response non trovata`).

Per esempio sull'errore 104 (Anomalia 19) la libreria ritorna: 
`Autenticazione fallita per ripetuta sottomissione di credenziali errate (superato numero tentativi secondo le policy adottate)`
Mentre AgID mi segnala: 
`Autenticazione fallita per ripetuta sottomissione di credenziali errate.`

**Comment by danielegiallonardo** [comment]
La modifica eventualmente richiederebbe un rilascio Major, dal momento che consiste in una modifica non retrocompatibile dei contracts (nel caso specifico cambierebbe il tipo dell'eccezione sollevata)

In tal caso comunque si potrebbe sollevare una "SpidException" che al suo interno contenga le seguenti property:
- Message: override della property Message della classe base Exception che contiene il messaggio da stampare a video (e.g. nel caso dell'errore 111 potrebbe essere "Errore generico")
- Reason: la motivazione legata al sollevamento dell'eccezione, da usare per troubleshooting (e.g. nel caso dell'errore 111 potrebbe essere "Signature Response non trovata")
- ErrorCode: codice di errore Spid (-1 per gli altri casi)

Questa modifica ha un impatto consistente, e riguarda tutti i punti in cui il codice solleva una eccezione, ivi compresi i metodi di validazione della response.

Sono aperto a PR.

**Comment by PiemP** [comment]
eh si ho visto.... io ci provo e spero di trovare tutti i punti in cui serve questa modifica. Su ErrorCode volevo utilizzare un enum per ogni test che AgID mi ha notificato di modo che un utente possa fare quello che vuole nel momento in cui intende customizzare un messaggio specifico.

Ovviamente se sei d'accordo su questa scelta e se sei d'accordo a non definire tutti e 112 gli enum in questo sviluppo...magari qualche dev di buon cuore quanto creera la sua issue e il PR per impementare gli enum mancanti.

**Comment by danielegiallonardo** [comment]
Nel momento in cui si rilascia una Major, e questa Major introduce una nuova gestione custom delle eccezioni, mi aspetto che tutti gli errorCode e tutti i messaggi delle regole tecniche di agid siano gestiti, la libreria a questo serve, fa lei il lavoro che dovrebbero fare gli altri. Capisco la tua necessità contingente, ma la libreria è a disposizione di tutti, non possiamo tirar fuori una versione che gestisce solo alcuni errori e non altri.

**Comment by PiemP** [comment]
Ho aperto una pull request in draft così puoi dare un occhio a quello che sto facendo di modo che se hai delle richieste da farmi possiamo già vederli durante il work in progress. 

Buon weekend e grazie.
