### ISSUE TITLE
Problemi vari nel processo di certificazione

### ISSUE THREAD

**Issue by lordnedox** [italia/spid-aspnetcore#69]
**Describe the bug**
Buongiorno a tutti, sto tentando da svariate settimane il processo di accreditamento come aggregatore/public/full utilizzando questa libreria. Sto utilizzando la versione 3.0 con i nuovi messaggi di errore.

Tuttavia non riesco a superare i test:
01. Response corretta
31. Response - Attributo Format di Issuer omesso
95. Assertion - Elemento AuthContextClassRef impostato suhttps://www.spid.gov.it/SpidL2
96. Assertion - Elemento AuthContextClassRef impostato suhttps://www.spid.gov.it/SpidL3
109. Attributi senza NameFormat

In realta' la response corretta mi sembra funzionare a dovere (utilizzando il validator locale), ed espongo una pagina di accesso effettuato correttamente elencando le credenziali ottenute (nome, CF, email).

Non so se questo sia il posto adattto a questo genere di problemi, ma non saprei dove altro chiedere.
Grazie in anticipo per l'aiuto!

**Comment by danielegiallonardo** [comment]
Salve,
quali sono gli errori riportati, relativi a quei test?
Cioè, quali sono le motivazioni per le quali le validazioni di quei test risultano fallite?

**Comment by lordnedox** [comment]
> Salve, quali sono gli errori riportati, relativi a quei test? Cioè, quali sono le motivazioni per le quali le validazioni di quei test risultano fallite?

Buongiorno Daniele,

L'unica indicazione fornita e' questa:

_Per quanto riguarda la response:
  ◦ Nei test 1, 31, 95, 96 e 109 l’utente deve accedere al servizio
      ◾ Per collaudare i test in cui l’utente deve accedere al servizio utilizziamo un’ utenza di test con il seguente
        codice fiscale TINIT-GDASDV00A01H501J
        Chiediamo quindi di censire nei vostri sistemi il codice fiscale sopra indicato, in modo da port eseguire i
        test_

Con allegato il report dei test dove indicati in rosso con la scritta "FAIL" i suddetti punti.

Tuttavia eseguendo il test 1 col validator locale io ottengo risultato positivo:
![SPID_REPONSE_OK](https://github.com/italia/spid-aspnetcore/assets/7017785/53195a92-2311-4f7a-9199-f973191f8ed6)

Grazie

**Comment by lordnedox** [comment]
Aggiungo che a mio avviso tutte le issues sono correlate alla numero 1 (accesso fallito). 

Nei logs vedo diverse chiamate in errore con il seguente codice:

--- MESSAGE: **Errore generico. Prova ad autenticarti più tardi.**
--- REASON: **Signature non valida**
--- SPID ERROR CODE: **ResponseFirmaNonValida**

Forse e' un errore sul certificato che ho generato utilizzando il tool? Oppure c'e' un certificato particolare da dover utilizzare?

grazie
Marco

**Comment by lordnedox** [comment]
Non so se sia questa la causa, ma verificando il metadato su https://validator.spid.gov.it/metadata.xml mi sembra che il valore di X509Certificate non corrisponda a quello della app di demo. Ho provato ad aggiornarlo, faro' sapere se questo dara' esito positivo.

**Comment by danielegiallonardo** [comment]
Prova a usare un certificato usando questo tool: https://github.com/italia/spid-compliant-certificates
Il certificato usato negli esempi potrebbe non essere compliant.

**Comment by lordnedox** [comment]
> Prova a usare un certificato usando questo tool: https://github.com/italia/spid-compliant-certificates Il certificato usato negli esempi potrebbe non essere compliant.

Avevo gia' generato il certificato usando quel tool, credo che il problema fosse proprio il X509Certificate che avevo copiato dalla web app di esempio dell SDK, ma che sul sito validator.spid.gov.it sembra avere un valore diverso.

Sottomesso di nuovo per la certificazione, adesso l'errore rilevato e' questo:
--- MESSAGE: Errore generico. Prova ad autenticarti più tardi.
--- REASON: **Attributo Assertion IssueIstant precedente a IssueInstant della richiesta**
--- SPID ERROR CODE:**AssertionIssueInstantPreRequest**

Su questo non avrei proprio idea dove agire...

**Comment by danielegiallonardo** [comment]
Il certificato, oltre che a firmare la request verso il validator, deve essere usato anche per firmare il metadata. Probabilmente il valore diverso dipende da questo. Se si cambia il certificato, bisogna ri-firmare il metadata, motivo per il quale la libreria mette a disposizione anche i middleware per generare un metadata firmato.

**Comment by lordnedox** [comment]
Confermo che il problema era il valore di ds:X509Certificate, che avevo copiato dalla app di esempio della SDK.

Il valore va aggiornato con l'ultimo disponibile nel metadata: https://validator.spid.gov.it/metadata.xml

Una volta aggiornato col valore corretto, sono riuscito a superare il test di validazione.

Grazie e alla prossima!

**Comment by danielegiallonardo** [comment]
Grazie per la segnalazione, provvedo a correggere gli appsettings delle app di esempio.
