### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by dassocec** [italia/spid-aspnetcore#7]
Sto cercando di gestire gli errori di autenticazione dell'utente (i classici errori 19,20,21,22,23,25) in produzione, ma non riesco a gestirli. Dalla guida non riesco a capire come integrare il codice per la visualizzazione degli errori all'utente. 
Qualcuno mi può aiutare? 
Grazie.

**Comment by danielegiallonardo** [comment]
Ciao,
è un po' difficile capire cosa c'è che non va senza vedere il codice. In particolare, in che modo non riesci a integrare il codice di esempio riportato nella guida?

**Comment by dassocec** [comment]
Il codice è identico alla soluzione scaricata. Non ho modificato nulla. In development mode vengono visualizzati i messaggi di errore. Scambiando in production viene visualizzata la pagina di errore generica. Ho notato che nello startup.cs c'è:

public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            else
            {
                app.UseExceptionHandler("/Home/Error");
                // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
                app.UseHsts();
            }

Come fare a visualizzare i messaggi di errore per l'utente? 
Il codice di esempio presente nella guida bisogna integrarlo nell'home controller?

**Comment by danielegiallonardo** [comment]
Nel caso riportato in guida, viene impostato il middleware per la gestione degli errori in modo tale che qualunque eccezione venga sollevata, la navigazione viene redirezionata verso l'action Error del controller Home (ma è assolutamente personalizzabile). Per cui, nel caso specifico dell'esempio, nel controller Home dovrà essere implementata una action Error contenente il codice di gestione dell'eccezione e verrà richiamata una View (presumibilmente una view razor "Error.cshtml") per la visualizzazione del messaggio d'errore all'utente.
Ad ogni modo questa gestione non ha nulla a che fare con la libreria SPID in sè (che si limita a lanciare una eccezione con un messaggio d'errore localizzato), quanto piuttosto con la gestione degli errori standard di AspNet.
Ti rinvio alla documentazione ufficiale di AspNet per approfondire la questione: [https://docs.microsoft.com/it-it/aspnet/core/web-api/handle-errors?view=aspnetcore-5.0](https://docs.microsoft.com/it-it/aspnet/core/web-api/handle-errors?view=aspnetcore-5.0)

**Comment by dassocec** [comment]
Grazie per la guida. Sto cercando di studiarla. 
Avrei bisogno di un esempio pratico di questo passaggio:
"nel controller Home dovrà essere implementata una action Error contenente il codice di gestione dell'eccezione e verrà richiamata una View (presumibilmente una view razor "Error.cshtml") per la visualizzazione del messaggio d'errore all'utente."

Altrimenti lasciando in produzione "Environment = development" può causare problemi?

**Comment by danielegiallonardo** [comment]
Si, esatto, l'ErrorViewModel può essere fatto così:

```csharp
public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId) && !string.IsNullOrEmpty(Message);

        public string Message { get; set; }
    }
```

**Comment by dassocec** [comment]
Non riesco a capire perchè, effettuando il test con il validator su docker, mi viene restituito un HTTP error 500...

**Comment by danielegiallonardo** [comment]
Credo ti convenga andare di debug, o analizzare i log applicativi. Ad ogni modo è un problema di integrazione con AspNet, non legato alla libreria, per cui chiudo la issue.
