### ISSUE TITLE
Lista IdP vuota

### ISSUE THREAD

**Issue by RossiNIT** [italia/spid-aspnetcore#70]
**Lista IdP vuota**
Cliccando il pulsante entra con SPID la lista è vuota. Ho notato che al sito registry.spid.gov.it è scaduto il certificato e per quello gli idp non vengono visualizzati, ma non vengono caricati neppure quelli di staging o se inserisco manualmente nell'appsettings gli idp.

**Screenshots**
![image](https://github.com/italia/spid-aspnetcore/assets/118269033/7c6a3112-ce71-47dd-a7b0-11ebf7d82e95)

**Comment by danielegiallonardo** [comment]
Salve, per ovviare a problematiche di questo tipo, con la versione 3.0.1 è possibile parametrizzare la durata della cache del metadata scaricato dal registry, ed è possibile eventualmente scaricare il json, renderlo "fruibile" su web (anche da un indirizzo self-hosted) e far puntare la libreria a quell'indirizzo modificando il parametro di configurazione IdPRegistryURL (occhio che in questo modo però non recepirà in automatico le modifiche che verranno fatte)
