### ISSUE TITLE
Error on Format request

### ISSUE THREAD

**Issue by ToosoftwareUser** [italia/spid-aspnetcore#74]
**Describe the bug**
Hi,when i click on the button SPID i receive an error
<img width="1103" alt="Screenshot 2024-04-19 at 10 47 22" src="https://github.com/italia/spid-aspnetcore/assets/8310205/765cc18d-83a6-4716-bfee-3959b3c85b13">

I tried to generate the certificates but it seems that I'm doing something wrong

**Comment by danielegiallonardo** [comment]
You cannot simply login into SPID with a self signed certificate. You should follow the on-boarding procedure with the authority.
You can start from here: https://www.spid.gov.it/cos-e-spid/diventa-fornitore-di-servizi/
