### ISSUE TITLE
QUESTION - `SpidOptions`, `PrincipalNameClaimType` valorizzata a Email by default

### ISSUE THREAD

**Issue by PiemP** [italia/spid-aspnetcore#75]
Buonasera,

ho una curiosità... come mai viene utilizzato il parametro che identifica l'email per inizializzare il valore della proprietà `PrincipalNameClaimType`... mi pare che SPID non impedisca che la stessa email possa essere utilizzata su utenti con anagrafiche differenti.

Personalmente, a me, attualmente accade che rischiamo di autenticarci ad un applicativo e trovare che un'altra utenza si è registrata con quella mail ma con un anagrafica differente dalla mia. So che SPID considera la mail come personale ma non è un vincolo indissolubile.

Grazie.

**Comment by danielegiallonardo** [comment]
Salve,
è impostato di default il claim Email come nome della Identity per compatibilità verso i sistemi di autenticazione più comuni, che usano la email come username.
Ad ogni modo è possibile specificare qualsivoglia claimtype nelle SpidOptions.
