### ISSUE TITLE
Errore generico durante la login spid dopo l'aggiornamento del pacchetto nuget

### ISSUE THREAD

**Issue by MithrandirTheWizard** [italia/spid-aspnetcore#77]
Aggiornando il pacchetto SPID.AspNetCore.Authentication alla versione 3.2.0 il sistema smette di funzionare per la maggior parte dei Provider SPID. Di seguito l'errore fornito da un IdP (Lepida):

An unhandled exception occurred while processing the request.
SpidException: AssertionConsumerService non correttamente valorizzato
SPID.AspNetCore.Authentication.Saml.SamlHandler.ValidateAuthnResponse(ResponseType response, AuthnRequestType request, IdentityProvider identityProvider, string serializedResponse)

AuthenticationFailureException: An error was encountered while handling the remote login.
Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler<TOptions>.HandleRequestAsync()

Stack Query Cookies Headers Routing
SpidException: AssertionConsumerService non correttamente valorizzato
SPID.AspNetCore.Authentication.Saml.SamlHandler.ValidateAuthnResponse(ResponseType response, AuthnRequestType request, IdentityProvider identityProvider, string serializedResponse)
SPID.AspNetCore.Authentication.SpidHandler.ValidateAuthenticationResponse(ResponseType response, AuthnRequestType request, AuthenticationProperties properties, string idpName, string serializedResponse)
SPID.AspNetCore.Authentication.SpidHandler.HandleRemoteAuthenticateAsync()

Show raw exception details
AuthenticationFailureException: An error was encountered while handling the remote login.
Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler<TOptions>.HandleRequestAsync()
Duende.IdentityServer.Hosting.FederatedSignOut.AuthenticationRequestHandlerWrapper.HandleRequestAsync() in AuthenticationRequestHandlerWrapper.cs
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Duende.IdentityServer.Hosting.DynamicProviders.DynamicSchemeAuthenticationMiddleware.Invoke(HttpContext context) in DynamicSchemeAuthenticationMiddleware.cs
Duende.IdentityServer.Hosting.BaseUrlMiddleware.Invoke(HttpContext context) in BaseUrlMiddleware.cs
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version 11

**Comment by PiemP** [comment]
stai utilizzando `AssertionConsumerServiceIndex` nelle configurazioni? Se si, ti consiglio di passare ad `AssertionConsumerServiceURL`... nella 3.2.0 viene rilasciata una modifica che fa in modo di inviare anche il parametro `ProtocolBinding` nelle richieste SAML verso gli IdP e questo fa si che la libreria funzioni meglio con questo parametro anche con i provider che hanno controlli più stringenti (es. alcuni considerano come attributo "valido" `AssertionConsumerServiceURL`, anche se valorizzato come stringa vuota nella richiesta SAML, e danno errore 16 se trovano valorizzato anche l'attributo `AssertionConsumerServiceIndex`)

ATTENZIONE che `AssertionConsumerServiceIndex` e `AssertionConsumerServiceURL` sono 2 parametri di configurazione che vanno in conflitto se valorizzati contemporaneamente... restando nell'ambito della modifica di configurazione ti consiglio di valorizzare `AssertionConsumerServiceIndex` con null.

Ci sono un pò di issue chiuse a riguardo.

**Comment by danielegiallonardo** [comment]
Il problema della 3.2.0 è che valorizza ProtocolBinding nella request a prescindere se sia stato indicato AssertionConsumerServiceURL, oppure AssertionConsumerServiceIndex, e questo "rompe" il protocollo.
