### ISSUE TITLE
Impossibile recuperare i service provider

### ISSUE THREAD

**Issue by fonts1215** [italia/spid-aspnetcore#80]
**Describe the bug**
utilizzando il componente "spid-providers" dallo scorso lunedi (15 luglio 2024) non riusciamo a recuperare i service provider, impedendo agli utenti di non potersi autenticare.

**Screenshots**
![image](https://github.com/user-attachments/assets/09e9365b-7912-47d4-a62b-a49d0df7484a)

**Desktop (please complete the following information):**
 - Version 3.3.0

**Comment by danielegiallonardo** [comment]
Ciao, credo abbiano modificato la url da cui la libreria leggeva la configurazione degli IdP. (https://registry.spid.gov.it/entities/?entity_type=idp&output=json)
Attualmente vedo che risponde su https://registry.spid.gov.it/entities/?entity_type=idp&output=json
Prova a impostare la variabile di configurazione "IdPRegistryURL" a questa seconda URL

**Comment by fonts1215** [comment]
Ciaom @danielegiallonardo , provato ma ancora niente settato cosi gli appsettings, nel dubbio ho disabilitato anche la cache 
![image](https://github.com/user-attachments/assets/3e9192ba-2c24-4da0-a9e0-40774f8eb80a)

**Comment by fonts1215** [comment]
Ciao @danielegiallonardo , si è rientrato tutto, procedo con la chiusura della issue! Grazie mille per il supporto
