### ISSUE TITLE
Uso dei punti d'estensione per il registro delle transazioni

### ISSUE THREAD

**Issue by gianlucabertani** [italia/spid-aspnetcore#9]
Il comma 2 dell'articolo 13 del DPCM richiede che i servire provider tengano un log dettagliato per 24 mesi di tutte le transazioni di autenticazione. Noi abbiamo integrato il progetto e la libreria nel nostro servizio e ottenuto l'approvazione da AgID. Stiamo ora cercando di mettere insieme questo registro delle transazioni. 

Ci siamo agganciati agli eventi indicati nei punti di estensione, però le strutture dati che ci vendono passate (AuthenticationSuccessContext, MessageReceivedContext ecc.) non sono documentate e facciamo una gran fatica a trovare le informazioni che dobbiamo loggare.

Nelle Regole Tecniche si fa riferimento a:

- \<AuthnRequest\>
- \<Response\>
- AuthnReq_ID
- AuthnReq_IssueInstant
- Resp_ID
- Resp_IssueInstant
- Resp_Issuer
- Assertion_ID
- Assertion_subject
- Assertion_subject_NameQualifier

Potreste indicarci dove trovare queste informazioni attraverso i context passati nei punti d'estensione? 

In particolare, mentre alcuni dati singoli (come l'authorization request ID) si possono intuire, non riusciamo a trovare un modo per recuperare l'XML di richiesta e risposta, da cui estrarre i blocchi \<AuthnRequest\> e \<Response\>, che vanno entrambi loggati.

Grazie mille in anticipo per qualsiasi aiuto vorrete fornici.

**Comment by danielegiallonardo** [comment]
Salve,
è possibile effettuare l'override dei seguenti SpidEvents:
- `OnRedirectToIdentityProvider` (per i messaggi di Request di Login e Logout): all'interno del `RedirectContext` è presente una property `SignedProtocolMessage` che può essere di tipo `AuthnRequestType` per le Request di Login e `LogoutRequestType` per le Request di Logout.
- `OnMessageReceived` (per i messaggi di Response): all'interno del `MessageReceivedContext` è presente una property `ProtocolMessage` di tipo `ResponseType`

Gli oggetti di cui sopra rappresentano la versione deserializzata delle Request e delle Response, è possibile procedere ad una nuova serializzazione (per esempio utilizzando XmlSerializer) nel caso in cui sia necessario salvare i messaggi Raw su uno storage esterno.

**Comment by gianlucabertani** [comment]
Grazie, ci proviamo.

**Comment by danielegiallonardo** [comment]
Aggiungo:
- `OnRemoteSignOut` (per i messaggi di Response di Logout): all'interno del `RemoteSignOutContext` è presente una property `ProtocolMessage` di tipo `LogoutResponseType`

**Comment by gianlucabertani** [comment]
Benissimo, grazie. 

Potresti indicarci anche a quali proprietà corrispondono gli altri campi indicati nelle Regole Tecniche:

- AuthnReq_ID
- AuthnReq_IssueInstant
- Resp_ID
- Resp_IssueInstant
- Resp_Issuer
- Assertion_ID
- Assertion_subject
- Assertion_subject_NameQualifier

Un'altra domanda: gli eventi di utenti diversi possono intercalarsi. C'è un ID o un token che possiamo usare per collegare con certezza il messaggio di response di un utente al relativo messaggio di request?

**Comment by gianlucabertani** [comment]
Niente, non c'è bisogno che rispondi. Abbiamo già trovato tutto.

Grazie mille.

**Comment by danielegiallonardo** [comment]
La correlazione tra response e request è possibile farla dal momento che (response.InResponseTo == request.ID).
Per quanto riguarda le altre property:
- AuthnReq_ID: request.ID
- AuthnReq_IssueInstant: request.IssueInstant
- Resp_ID: response.InResponseTo
- Resp_IssueInstant: response.IssueInstant
- Resp_Issuer: response.Issuer
- Assertion_ID: (response.Items.FirstOrDefault(s => s is AssertionType) as AssertionType)?.ID
- Assertion_subject: (response.Items.FirstOrDefault(s => s is AssertionType) as AssertionType)?.Subject
- Assertion_subject_NameQualifier: ((response.Items.FirstOrDefault(s => s is AssertionType) as AssertionType)?.Subject.Items.FirstOrDefault(s => s is NameIDType) as NameIDType).NameQualifier

**Comment by dassocec** [comment]
Scusate la domanda banale, ma in quale parte di codice è possibile intercettare questi valori?

**Comment by danielegiallonardo** [comment]
Nei CustomSpidEvents

**Comment by dassocec** [comment]
Ok, grazie per l'indicazione, ma quando inserisco quei valori nel customspidevents, mi dà errore su "request" e "response" : mi dice che non esistono nel contesto corrente.
